import { THREE, C, TwinEngine, mat, box, flatPlane, textPlane } from './core.js';
import { desk, chair, monitor, workstation, cabinet, equipmentModel } from './models.js';
import { SITE, BUILDINGS, CLASSROOMS, FLOOR_TWIN, LABS } from '../data/digital-twin-data.js';

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const viewport=$('#viewport'),labels=$('#labels'),detail=$('#detail'),quickbar=$('#quickbar'),loader=$('#loader');
let map2d=$('#map2d');if(!map2d){map2d=document.createElement('div');map2d.id='map2d';map2d.className='map2d';map2d.hidden=true;viewport.appendChild(map2d)}
let classroomList=$('#classroomList');if(!classroomList){const t=document.createElement('div');t.className='section-title';t.textContent='GENERAL / COMPUTER CLASSROOMS';classroomList=document.createElement('div');classroomList.id='classroomList';classroomList.className='lab-list';const labList=$('#labList');labList.insertAdjacentElement('afterend',classroomList);classroomList.insertAdjacentElement('beforebegin',t)}
if(!$('#mapModeBtn')){const b=document.createElement('button');b.id='mapModeBtn';b.textContent='2D / 3D';$('#overviewBtn').insertAdjacentElement('beforebegin',b)}
if($('#labsTab'))$('#labsTab').textContent='室內 Twin';

const campus=await fetch('./data/campus.geojson',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('campus.geojson');return r.json()});
const engine=new TwinEngine(viewport,labels);const world=engine.world;
const state={mode:'campus',floor:6,lab:'E-609',classroom:'E-510',equipment:null,view2d:false};
const colors={E:C.cyan,T1:0x466d83,T2:0x3b6278,D:0x496c84,M:0x355a70,G:0x4b6878,L:0x355f77,A:0x395666,ATH:0x45606d};

const geoToLocal=([lon,lat])=>{const[clon,clat]=SITE.campusCenter;return[(lon-clon)*Math.cos(clat*Math.PI/180)*111320,-(lat-clat)*110540]};
function fCenter(f){const pts=f.geometry.coordinates[0].map(geoToLocal),v=pts.reduce((a,p)=>[a[0]+p[0],a[1]+p[1]],[0,0]);return[v[0]/pts.length,v[1]/pts.length]}
const feature=code=>campus.features.find(f=>f.properties.code===code);
function extrude(f){const pts=f.geometry.coordinates[0].map(geoToLocal),s=new THREE.Shape();pts.forEach(([x,z],i)=>i?s.lineTo(x,-z):s.moveTo(x,-z));const h=f.properties.height||f.properties.levels*3.6,g=new THREE.ExtrudeGeometry(s,{depth:h,bevelEnabled:false});g.rotateX(-Math.PI/2);const m=new THREE.Mesh(g,mat(colors[f.properties.code]||C.blue,{roughness:.5,metalness:.1,emissive:f.properties.code==='E'?0x07303c:0x061018,emissiveIntensity:.35}));m.castShadow=true;m.receiveShadow=true;return m}
function campusGround(){world.add(flatPlane(240,200,0x102b3b));const grid=new THREE.GridHelper(240,32,0x2b6179,0x1b3848);grid.position.y=.03;world.add(grid)}
function hideLoader(){loader.hidden=true}

function set2D(show){state.view2d=show;map2d.hidden=!show;engine.renderer.domElement.style.visibility=show?'hidden':'visible';labels.style.visibility=show?'hidden':'visible';$('#mapModeBtn').textContent=show?'回到 3D':'2D / 3D';if(show)draw2D()}
function draw2D(){const feats=campus.features,pts=feats.flatMap(f=>f.geometry.coordinates[0].map(geoToLocal)),xs=pts.map(p=>p[0]),zs=pts.map(p=>p[1]),minX=Math.min(...xs)-12,maxX=Math.max(...xs)+12,minZ=Math.min(...zs)-12,maxZ=Math.max(...zs)+12,W=900,H=620,sx=x=>(x-minX)/(maxX-minX)*W,sy=z=>(z-minZ)/(maxZ-minZ)*H;const polys=feats.map(f=>{const p=f.properties,points=f.geometry.coordinates[0].map(geoToLocal).map(([x,z])=>`${sx(x)},${sy(z)}`).join(' '),[cx,cz]=fCenter(f);return `<polygon class="building ${p.code==='E'?'target':''}" data-code="${p.code}" points="${points}"/><text class="bcode" x="${sx(cx)}" y="${sy(cz)-3}" text-anchor="middle">${p.code}</text><text class="bname" x="${sx(cx)}" y="${sy(cz)+10}" text-anchor="middle">${p.name}</text>`}).join('');map2d.innerHTML=`<svg viewBox="0 0 ${W} ${H}"><rect class="site-bg" x="5" y="5" width="${W-10}" height="${H-10}" rx="22"/><path class="road" d="M ${sx(minX+8)} ${sy((minZ+maxZ)/2)} L ${sx(maxX-8)} ${sy((minZ+maxZ)/2)}"/><path class="road" d="M ${sx((minX+maxX)/2)} ${sy(minZ+6)} L ${sx((minX+maxX)/2)} ${sy(maxZ-6)}"/>${polys}</svg><div class="legend2d"><b>CYUT Campus 2D</b><br>同一份 campus.geojson 與 3D 場景同步<br>點選建物查看工管學生可用空間</div>`;$$('[data-code]',map2d).forEach(el=>el.onclick=()=>{const code=el.dataset.code;set2D(false);if(code==='E')renderBuilding();else{renderCampus();setTimeout(()=>focusBuilding(code),30)}})}

function focusBuilding(code){const f=feature(code),b=BUILDINGS[code];if(!f){showBuilding({code,name:b?.name||code,name_en:b?.en||'',levels:'—'});return}const p=f.properties,[cx,cz]=fCenter(f);engine.setCamera(.78,.4,42,new THREE.Vector3(cx,(p.height||p.levels*3.6)*.22,cz),12,130);showBuilding(p)}
function renderCampus(){engine.clear();set2D(false);state.mode='campus';state.equipment=null;sync();campusGround();for(const f of campus.features){const p=f.properties,m=extrude(f);engine.addPick(m,()=>p.code==='E'?renderBuilding():focusBuilding(p.code));world.add(m);const[cx,cz]=fCenter(f),a=engine.labelAnchor(cx,(p.height||p.levels*3.6)+2,cz,m.userData.action);engine.addLabel(a,`${p.code}｜${p.name}`,p.code==='E'?'target':'')}engine.setCamera(.78,.48,115,new THREE.Vector3(0,8,0),20,180);showCampus();quickCampus();hideLoader()}

function eShape(scale=.28){const f=feature('E'),pts=f.geometry.coordinates[0].map(geoToLocal),c=fCenter(f),s=new THREE.Shape();pts.forEach(([x,z],i)=>{const X=(x-c[0])*scale,Z=-(z-c[1])*scale;i?s.lineTo(X,Z):s.moveTo(X,Z)});return s}
function slab(shape,y,color,opacity=1){const g=new THREE.ExtrudeGeometry(shape,{depth:.22,bevelEnabled:false});g.rotateX(-Math.PI/2);g.translate(0,y,0);const m=new THREE.Mesh(g,mat(color,{transparent:opacity<1,opacity,roughness:.6}));m.castShadow=true;m.receiveShadow=true;return m}
function renderBuilding(){engine.clear();set2D(false);state.mode='building';sync();const sh=eShape();world.add(flatPlane(34,30,0x112a38));for(let f=1;f<=7;f++){const y=(f-1)*2.15+.15,active=f===5||f===6,s=slab(sh,y,active?(f===6?0x3995a8:0x5f7eb4):0x345061,active?.82:.36);if(active)engine.addPick(s,()=>renderFloor(f));world.add(s);const a=engine.labelAnchor(8.8,y+1,-6.3+f*.12,active?()=>renderFloor(f):()=>showPassiveFloor(f));engine.addLabel(a,`${f}F${active?' · IEM':''}`,active?'floor':'')}engine.setCamera(.78,.48,48,new THREE.Vector3(0,7,0),10,80);showEBuilding();quickBuilding();hideLoader()}

const rcolors={lab:0x218095,office:0x3c6d9d,seminar:0x63528f,meeting:0x9b763c,classroom:0x3f7a68};
function renderFloor(n){engine.clear();set2D(false);state.mode='floor';state.floor=n;sync();const base=box(17,.18,12,0x193544);base.position.y=.1;world.add(base);const corridor=box(14.5,.04,1.3,0x66737a);corridor.position.set(.2,.22,.1);world.add(corridor);for(const r of FLOOR_TWIN[n].rooms){const g=box(r.w,.55,r.d,rcolors[r.kind]||C.blue);g.position.set(r.x,.48,r.z);const action=r.lab?()=>renderLab(r.code):r.classroom?()=>renderClassroom(r.code):()=>showRoom(r);engine.addPick(g,action);world.add(g);const a=engine.labelAnchor(r.x,1.55,r.z,action);engine.addLabel(a,`${r.code} ${r.name}`,r.lab||r.classroom?'floor':'')}engine.setCamera(.7,.7,32,new THREE.Vector3(0,.4,0),8,60);showFloor(n);quickFloor(n);hideLoader()}

function roomShell(lab){const {w,d,h,pattern='vinyl',wall='lab',windows=[]}=lab.room,g=new THREE.Group(),floor=flatPlane(w,d,pattern==='tile'?0xd7ceb5:0xded8cf);g.add(floor);if(pattern==='tile'){for(let x=-w/2;x<=w/2;x+=1.2){const q=box(.018,.012,d,0x4b5056);q.position.set(x,.015,0);g.add(q)}for(let z=-d/2;z<=d/2;z+=1.2){const q=box(w,.012,.018,0x4b5056);q.position.set(0,.016,z);g.add(q)}}const wc=wall==='e609'?0xf2eee8:0xf1f0ec;const back=box(w,h,.12,wc);back.position.set(0,h/2,-d/2);g.add(back);const left=box(.12,h,d,wc);left.position.set(-w/2,h/2,0);g.add(left);const right=box(.12,h,d,wc);right.position.set(w/2,h/2,0);g.add(right);const beam=0xe7e7e3;[[w,.06,.12,0,h,-d/2+.06],[.12,.06,d,-w/2+.06,h,0],[.12,.06,d,w/2-.06,h,0],[w,.06,.12,0,h,d/2-.06]].forEach(([a,b,c,x,y,z])=>{const q=box(a,b,c,beam);q.position.set(x,y,z);g.add(q)});for(let x=-w/2+1.5;x<w/2-1;x+=3.2){const q=box(.04,.04,d-1,0xdfdfdb);q.position.set(x,h-.03,0);g.add(q)}for(let z=-d/2+1.4;z<d/2-1;z+=3){const q=box(w-1,.04,.04,0xdfdfdb);q.position.set(0,h-.03,z);g.add(q)}for(let x=-w/2+1.6;x<w/2-1.2;x+=3.2)for(let z=-d/2+1.6;z<d/2-1;z+=3){const q=box(1.45,.028,.55,0xffffff);q.material.emissive=new THREE.Color(0xe8f2ff);q.material.emissiveIntensity=.55;q.position.set(x,h-.07,z);g.add(q)}for(const win of windows){const glass=box(win.w,win.h,.03,0xaed0de);glass.material.transparent=true;glass.material.opacity=.25;const frame=box(win.w+.18,win.h+.18,.06,0xd4d6d6);if(win.wall==='back'){frame.position.set(win.x,win.y,-d/2+.055);glass.position.set(win.x,win.y,-d/2+.08)}else{frame.position.set(w/2-.055,win.y,win.x);frame.rotation.y=Math.PI/2;glass.position.set(w/2-.08,win.y,win.x);glass.rotation.y=Math.PI/2}g.add(frame,glass);if(win.curtains){const cur=box(win.w+.05,win.h*.95,.05,0xd5cebf);if(win.wall==='back')cur.position.set(win.x,win.y-.05,-d/2+.11);else{cur.position.set(w/2-.11,win.y-.05,win.x);cur.rotation.y=Math.PI/2}g.add(cur)}}if(lab.code==='E-609'){const ac=box(1.65,.42,.38,0xefefef);ac.position.set(-5.6,2.75,-d/2+.28);g.add(ac)}const sign=textPlane(lab.name,lab.en,Math.min(7,w*.45),1.35);sign.position.set(-w/2+.08,2.15,0);sign.rotation.y=Math.PI/2;g.add(sign);return g}
function renderLab(code){const lab=LABS[code];if(!lab)return;engine.clear();set2D(false);state.mode='lab';state.lab=code;state.floor=lab.floor;state.equipment=null;sync();world.add(roomShell(lab));for(const item of lab.equipment){const g=equipmentModel(item);engine.addPick(g,()=>focusEquipment(item,g));world.add(g);if(item.major){const a=engine.labelAnchor(item.x,2.2,item.z,g.userData.action);engine.addLabel(a,item.name,item.provenance==='current'?'current':'')}}if(code==='E-609'){for(const x of[-6.9,-5.4,-3.9]){const c=cabinet(1.1,1.4,.42);c.position.set(x,0,-4.25);world.add(c)}for(const x of[5.8,7]){const c=cabinet(1.05,1.2,.42);c.position.set(x,0,-2.3);c.rotation.y=Math.PI/2;world.add(c)}const t=desk(3.1,1);t.position.set(4.7,0,-3.9);world.add(t);for(const [x,z,r] of[[-.95,5.05,Math.PI],[.95,5.05,Math.PI],[-5.9,4.5,.6]]){const c=chair();c.position.set(x,0,z);c.rotation.y=r;world.add(c)}}const v=lab.entryView;engine.setCamera(v.yaw,v.pitch,v.dist,new THREE.Vector3(...v.target),4,45);showLab(lab);quickLab(lab);hideLoader()}
function focusEquipment(item,g){state.equipment=item.id;const p=g.getWorldPosition(new THREE.Vector3());engine.setCamera(engine.cam.gyaw,.34,6.2,new THREE.Vector3(p.x,1.05,p.z),2.8,18);showEquipment(item,LABS[state.lab]);quickActive()}

function classroomShell(c){const {w,d,h}=c.room,g=new THREE.Group();g.add(flatPlane(w,d,0xd8cfb8));for(let x=-w/2;x<=w/2;x+=1.2){const q=box(.014,.01,d,0x4f5357);q.position.set(x,.012,0);g.add(q)}for(let z=-d/2;z<=d/2;z+=1.2){const q=box(w,.01,.014,0x4f5357);q.position.set(0,.013,z);g.add(q)}for(const [a,b,dd,x,y,z] of[[w,.12,.12,0,h,-d/2],[.12,h,d,-w/2,h/2,0],[.12,h,d,w/2,h/2,0]]){const q=box(a,b,dd,0xf0eee8);q.position.set(x,y,z);g.add(q)}for(let x=-w/2+1.4;x<w/2-1;x+=3){const q=box(.04,.04,d-1,0xe4e4df);q.position.set(x,h-.04,0);g.add(q)}for(let z=-d/2+1.2;z<d/2-1;z+=2.7){const q=box(w-1,.04,.04,0xe4e4df);q.position.set(0,h-.04,z);g.add(q)}for(let x=-w/2+1.5;x<w/2-1;x+=3)for(let z=-d/2+1.5;z<d/2-1;z+=2.7){const l=box(1.35,.025,.5,0xffffff);l.material.emissive=new THREE.Color(0xe8f2ff);l.material.emissiveIntensity=.48;l.position.set(x,h-.07,z);g.add(l)}const board=box(w*.55,1.35,.06,0x20262c);board.position.set(0,1.8,-d/2+.13);g.add(board);const pod=desk(1.25,.62);pod.position.set(-w*.31,0,-d*.32);g.add(pod);const win=box(.04,1.15,d*.48,0xaed5e4);win.material.transparent=true;win.material.opacity=.25;win.position.set(w/2-.08,1.75,.6);g.add(win);return g}
function studentDeskPair(){const g=new THREE.Group();for(const x of[-.36,.36]){const d=desk(.68,.48);d.scale.y=.9;d.position.x=x;g.add(d);const c=chair(0x647784);c.position.set(x,0,.48);g.add(c)}return g}
function computerDesk(){const g=desk(1.25,.65),m=monitor();m.scale.set(.72,.72,.72);m.position.set(0,.82,-.1);g.add(m);const c=chair(0x426b8a);c.position.set(0,0,.55);g.add(c);return g}
function renderClassroom(code){const c=CLASSROOMS[code];if(!c)return;engine.clear();set2D(false);state.mode='classroom';state.classroom=code;state.floor=c.floor;sync();world.add(classroomShell(c));if(c.type==='computer'){const rows=c.layout.rows,cols=c.layout.cols,dx=c.room.w/(cols+1),dz=(c.room.d-2.2)/rows;for(let r=0;r<rows;r++)for(let k=0;k<cols;k++){const d=computerDesk();d.position.set(-c.room.w/2+dx*(k+1),0,-c.room.d/2+2+dz*r);d.rotation.y=Math.PI;world.add(d)}}else{const rows=c.layout.rows,cols=Math.ceil(c.layout.cols/2),dx=c.room.w/(cols+1),dz=(c.room.d-2.1)/rows;for(let r=0;r<rows;r++)for(let k=0;k<cols;k++){const d=studentDeskPair();d.position.set(-c.room.w/2+dx*(k+1),0,-c.room.d/2+1.8+dz*r);d.rotation.y=Math.PI;world.add(d)}}engine.setCamera(.72,.34,Math.max(c.room.w,c.room.d)*1.35,new THREE.Vector3(0,1.15,.5),4,36);showClassroom(c);quickClassroom(c);hideLoader()}

function badge(p){return `<span class="badge ${p==='official'?'official':'current'}">${p==='official'?'官方公開設備／功能':'現況／場域配置'}</span>`}
function showCampus(){const cards=Object.values(BUILDINGS).map(b=>`<div class="equip"><strong>${b.code}｜${b.name}</strong><small>${b.role} · ${(b.iemAccess||[]).join('、')}</small></div>`).join('');detail.innerHTML=`<div class="kicker">FULL CAMPUS GUIDE</div><h2>朝陽校園完整導覽</h2><div class="en">CYUT Digital Twin Guide</div><div class="desc">同一份本地 campus.geojson 同步驅動 2D 與 3D。校園資訊面板補入工管學生會使用的教學、管理、資訊、人文科技、圖書館等空間。</div><div class="metric-grid"><div class="metric"><span>Mode</span><b>2D + 3D</b></div><div class="metric"><span>Runtime</span><b>Offline GeoJSON</b></div><div class="metric"><span>Lab Twins</span><b>${Object.keys(LABS).length}</b></div><div class="metric"><span>Classroom Twins</span><b>${Object.keys(CLASSROOMS).length}</b></div></div><div class="section-title">MAJOR BUILDINGS</div>${cards}<div class="linkrow"><a href="${SITE.sources.cyutCampus}" target="_blank">官方校園平面圖 ↗</a><a href="${SITE.sources.cyutBuildings}" target="_blank">各大樓樓層 ↗</a></div>`}
function showBuilding(p){const b=BUILDINGS[p.code]||{role:'校園建物',description:'校園導覽建物。',iemAccess:[]};const cs=Object.values(CLASSROOMS).filter(c=>c.building===p.code);detail.innerHTML=`<div class="kicker">CAMPUS BUILDING</div><h2>${p.code}｜${p.name}</h2><div class="en">${p.name_en||b.en||''}</div><div class="desc">${b.description}</div><div class="metric-grid"><div class="metric"><span>樓層</span><b>${p.levels||'—'}F</b></div><div class="metric"><span>定位</span><b>${b.role}</b></div></div><div class="section-title">IEM STUDENT SPACES</div>${(b.iemAccess||[]).map(x=>`<div class="equip"><strong>${x}</strong></div>`).join('')}${cs.length?`<div class="section-title">3D CLASSROOMS</div>${cs.map(c=>`<div class="equip"><strong>${c.code}｜${c.name}</strong><small>${c.type==='computer'?'電腦教室':'普通教室'}</small><button class="inline-open" data-open-classroom="${c.code}">進入 3D</button></div>`).join('')}`:''}${p.code==='E'?'<div class="linkrow"><button id="openE">進入理工大樓 Twin</button></div>':''}`;$$('[data-open-classroom]',detail).forEach(x=>x.onclick=()=>renderClassroom(x.dataset.openClassroom));if($('#openE'))$('#openE').onclick=renderBuilding}
function showEBuilding(){detail.innerHTML=`<div class="kicker">SCIENCE & ENGINEERING BUILDING</div><h2>E｜理工大樓</h2><div class="desc">7 層 cutaway，工管系主要空間集中在 5F／6F。可進入 E-510 一般教室或各實驗室設備級 Twin。</div><div class="linkrow"><button data-f="5">進入 5F</button><button data-f="6">進入 6F</button></div>`;$$('[data-f]',detail).forEach(b=>b.onclick=()=>renderFloor(+b.dataset.f))}
function showFloor(n){detail.innerHTML=`<div class="kicker">${n}F FLOOR TWIN</div><h2>理工大樓 ${n}F</h2><div class="desc">依工管系公開樓層配置重建房間關係；普通教室與實驗室可繼續進入 3D。</div>${FLOOR_TWIN[n].rooms.map(r=>`<div class="equip"><strong>${r.code}｜${r.name}</strong><small>${r.lab?'Lab Twin':r.classroom?'Classroom Twin':'Floor context'}</small></div>`).join('')}`}
const showRoom=r=>detail.innerHTML=`<div class="kicker">ROOM</div><h2>${r.code}</h2><div class="en">${r.name}</div>`;
const showPassiveFloor=n=>detail.innerHTML=`<div class="kicker">BUILDING FLOOR</div><h2>${n}F</h2><div class="desc">目前不在工管細部 Twin 範圍。</div>`;
function showLab(l){detail.innerHTML=`<div class="kicker">LAB DIGITAL TWIN</div><h2>${l.code}｜${l.name}</h2><div class="en">${l.en}</div><div class="desc">${l.publicDescription}</div>${l.previousPublicName?`<div class="sourcebox">公開頁舊名稱：${l.previousPublicName}；目前場域以「${l.name}」呈現。</div>`:''}<div class="section-title">RESEARCH</div><div class="tags">${l.research.map(x=>`<span class="tag">${x}</span>`).join('')}</div><div class="section-title">EQUIPMENT</div>${l.equipment.map(e=>`<div class="equip">${badge(e.provenance)}<strong>${e.name}</strong><small>${e.model}</small></div>`).join('')}<div class="linkrow"><a href="${l.source}" target="_blank">官方實驗室資料 ↗</a></div>`}
function showEquipment(e,l){detail.innerHTML=`<div class="kicker">EQUIPMENT TWIN</div><h2>${e.name}</h2><div class="en">${l.code} · ${l.name}</div>${badge(e.provenance)}<div class="desc">設備以低多邊形外型、相對尺寸與場域位置呈現。</div><div class="linkrow"><button id="backLab">回到實驗室全景</button></div>`;$('#backLab').onclick=()=>renderLab(l.code)}
function showClassroom(c){detail.innerHTML=`<div class="kicker">CLASSROOM DIGITAL TWIN</div><h2>${c.code}｜${c.name}</h2><div class="en">${c.en}</div><div class="desc">${c.notes}</div><span class="classroom-badge">${c.type==='computer'?'電腦教室':'普通教室'}</span><div class="metric-grid"><div class="metric"><span>Building</span><b>${c.building}</b></div><div class="metric"><span>Floor</span><b>${c.floor}F</b></div>${c.layout.computers?`<div class="metric"><span>PCs</span><b>${c.layout.computers}</b></div>`:''}</div><div class="classroom-note">場景採開放式 cutaway 天花骨架、燈具、窗、講台、桌椅；電腦教室另配置螢幕與工作站，不再以盒狀房間呈現。</div><div class="linkrow"><a href="${c.source}" target="_blank">官方空間資料 ↗</a></div>`}

function wire(){$$('[data-building]',quickbar).forEach(b=>b.onclick=()=>b.dataset.building==='E'?renderBuilding():focusBuilding(b.dataset.building));$$('[data-floor]',quickbar).forEach(b=>b.onclick=()=>renderFloor(+b.dataset.floor));$$('[data-lab]',quickbar).forEach(b=>b.onclick=()=>renderLab(b.dataset.lab));$$('[data-classroom]',quickbar).forEach(b=>b.onclick=()=>renderClassroom(b.dataset.classroom));$$('[data-eq]',quickbar).forEach(b=>b.onclick=()=>{const item=LABS[state.lab].equipment.find(x=>x.id===b.dataset.eq),obj=world.children.find(o=>o.userData.action&&Math.abs(o.position.x-item.x)<.01&&Math.abs(o.position.z-item.z)<.01);if(obj)focusEquipment(item,obj)})}
function quickCampus(){quickbar.innerHTML=Object.values(BUILDINGS).filter(b=>b.modeled).map(b=>`<button class="quick" data-building="${b.code}"><strong>${b.code}</strong>${b.name}</button>`).join('')+Object.values(CLASSROOMS).slice(0,4).map(c=>`<button class="quick" data-classroom="${c.code}"><strong>${c.code}</strong>${c.name}</button>`).join('');wire()}
function quickBuilding(){quickbar.innerHTML='<button class="quick" data-floor="5"><strong>5F</strong>辦公／教室／機電</button><button class="quick" data-floor="6"><strong>6F</strong>研究實驗室</button>';wire()}
function quickFloor(n){quickbar.innerHTML=FLOOR_TWIN[n].rooms.map(r=>`<button class="quick" ${r.lab?`data-lab="${r.code}"`:r.classroom?`data-classroom="${r.code}"`:''}><strong>${r.code}</strong>${r.name}</button>`).join('');wire()}
function quickLab(l){quickbar.innerHTML=`<button class="quick active" data-lab="${l.code}"><strong>${l.code}</strong>全景</button>`+l.equipment.map(e=>`<button class="quick" data-eq="${e.id}"><strong>•</strong>${e.name}</button>`).join('');wire()}
function quickClassroom(c){quickbar.innerHTML=`<button class="quick active" data-classroom="${c.code}"><strong>${c.code}</strong>${c.name}</button><button class="quick" data-building="${c.building}"><strong>${c.building}</strong>回建物</button>`;wire()}
function quickActive(){$$('.quick',quickbar).forEach(b=>b.classList.toggle('active',b.dataset.eq===state.equipment))}

function sync(){const mode=state.mode==='floor'?'building':state.mode==='classroom'?'lab':state.mode;$$('.sidebtn').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#campusTab').classList.toggle('active',state.mode==='campus');$('#buildingTab').classList.toggle('active',state.mode==='building'||state.mode==='floor');$('#labsTab').classList.toggle('active',state.mode==='lab'||state.mode==='classroom');if(state.mode==='campus'){$('#navTitle').textContent='完整校園導覽';$('#navSubtitle').textContent='2D/3D 對照、主要大樓與工管學生常用空間。';$('#crumb').textContent='CYUT / Campus';$('#sceneTitle').textContent='朝陽校園 2D / 3D Guide'}else if(state.mode==='building'){$('#navTitle').textContent='理工大樓';$('#navSubtitle').textContent='7F cutaway，5F / 6F 可進入。';$('#crumb').textContent='CYUT / E';$('#sceneTitle').textContent='理工大樓 Cutaway'}else if(state.mode==='floor'){$('#navTitle').textContent=`理工大樓 ${state.floor}F`;$('#crumb').textContent=`CYUT / E / ${state.floor}F`;$('#sceneTitle').textContent=`${state.floor}F Floor Twin`}else if(state.mode==='lab'){const l=LABS[state.lab];$('#navTitle').textContent=`${l.code} ${l.name}`;$('#navSubtitle').textContent=l.publicDescription;$('#crumb').textContent=`CYUT / E / ${l.floor}F / ${l.code}`;$('#sceneTitle').textContent=l.name}else{const c=CLASSROOMS[state.classroom];$('#navTitle').textContent=`${c.code} ${c.name}`;$('#navSubtitle').textContent=c.notes;$('#crumb').textContent=`CYUT / ${c.building} / ${c.floor}F / ${c.code}`;$('#sceneTitle').textContent=c.name}}

function buildLists(){$('#labList').innerHTML=Object.values(LABS).map(l=>`<button class="labbtn" data-lab="${l.code}"><strong>${l.code}｜${l.name}</strong><small>${l.floor}F · ${l.research.slice(0,3).join(' · ')}</small></button>`).join('');$$('[data-lab]',$('#labList')).forEach(b=>b.onclick=()=>renderLab(b.dataset.lab));classroomList.innerHTML=Object.values(CLASSROOMS).map(c=>`<button class="labbtn" data-classroom="${c.code}"><strong>${c.code}｜${c.name}</strong><small>${c.building} · ${c.floor}F · ${c.type==='computer'?'電腦教室':'普通教室'}</small></button>`).join('');$$('[data-classroom]',classroomList).forEach(b=>b.onclick=()=>renderClassroom(b.dataset.classroom))}
const idx=[];for(const [code,b] of Object.entries(BUILDINGS))idx.push({type:'building',code,name:b.name,sub:b.role,text:[code,b.name,b.en,b.role,...b.iemAccess].join(' ').toLowerCase()});for(const c of Object.values(CLASSROOMS))idx.push({type:'classroom',code:c.code,name:c.name,sub:`${c.building} · ${c.floor}F`,text:[c.code,c.name,c.en,c.type].join(' ').toLowerCase(),classroom:c.code});for(const l of Object.values(LABS)){idx.push({type:'lab',code:l.code,name:l.name,sub:`${l.floor}F`,text:[l.code,l.name,l.en,...l.research].join(' ').toLowerCase(),lab:l.code});for(const e of l.equipment)idx.push({type:'equipment',code:l.code,name:e.name,sub:l.name,text:[e.name,e.model,l.code,l.name].join(' ').toLowerCase(),lab:l.code,eq:e.id})}
function search(q){const box=$('#searchResults');q=q.trim().toLowerCase();if(!q){box.hidden=true;return}const toks=q.split(/\s+/),res=idx.filter(x=>toks.every(t=>x.text.includes(t))).slice(0,18);box.hidden=false;box.innerHTML=res.length?res.map((r,i)=>`<button class="result" data-i="${i}"><code>${r.code}</code><span><b>${r.name}</b><small>${r.sub}</small></span><em>${r.type==='equipment'?'設備':r.type==='lab'?'實驗室':r.type==='classroom'?'教室':'建物'}</em></button>`).join(''):'<div class="sourcebox">找不到相符項目</div>';$$('[data-i]',box).forEach(b=>b.onclick=()=>{const r=res[+b.dataset.i];box.hidden=true;if(r.type==='building')r.code==='E'?renderBuilding():focusBuilding(r.code);else if(r.type==='classroom')renderClassroom(r.classroom);else{renderLab(r.lab);if(r.eq)setTimeout(()=>{const item=LABS[r.lab].equipment.find(x=>x.id===r.eq),obj=world.children.find(o=>o.userData.action&&Math.abs(o.position.x-item.x)<.01&&Math.abs(o.position.z-item.z)<.01);if(obj)focusEquipment(item,obj)},60)}})}

function overview(){if(state.mode==='campus')engine.setCamera(.78,.48,115,new THREE.Vector3(0,8,0),20,180);else if(state.mode==='building')engine.setCamera(.78,.48,48,new THREE.Vector3(0,7,0),10,80);else if(state.mode==='floor')engine.setCamera(.7,.7,32,new THREE.Vector3(0,.4,0),8,60);else if(state.mode==='classroom'){const c=CLASSROOMS[state.classroom];engine.setCamera(.72,.34,Math.max(c.room.w,c.room.d)*1.35,new THREE.Vector3(0,1.15,.5),4,36)}else{const l=LABS[state.lab],v=l.entryView;engine.setCamera(v.yaw,v.pitch,v.dist,new THREE.Vector3(...v.target),4,45)}}
function walk(){if(state.mode==='classroom'){const c=CLASSROOMS[state.classroom];engine.setCamera(0,.08,5.2,new THREE.Vector3(0,1.25,-c.room.d*.32),2.2,16)}else if(state.mode==='lab'){const l=LABS[state.lab],v=l.walkView;engine.setCamera(v.yaw,v.pitch,v.dist,new THREE.Vector3(...v.target),2.5,18)}}

$('#brandHome').onclick=()=>renderCampus();$('#campusTab').onclick=renderCampus;$('#buildingTab').onclick=renderBuilding;$('#labsTab').onclick=()=>renderLab(state.lab);$$('.sidebtn').forEach(b=>b.onclick=()=>b.dataset.mode==='campus'?renderCampus():b.dataset.mode==='building'?renderBuilding():renderLab(state.lab));$('#overviewBtn').onclick=overview;$('#walkBtn').onclick=walk;$('#resetBtn').onclick=overview;$('#mapModeBtn').onclick=()=>{if(state.mode!=='campus'){renderCampus();setTimeout(()=>set2D(true),50)}else set2D(!state.view2d)};$('#searchInput').oninput=e=>search(e.target.value);
buildLists();renderCampus();
