(() => {
  'use strict';
  const DATA = window.IEM_DATA;
  const FALLBACK = window.CYUT_FALLBACK_BUILDINGS || {type:'FeatureCollection',features:[{type:'Feature',properties:{osm_id:292141618,name:'理工大樓',building:'school',levels:7,height:25.2,source_status:'built-in fallback'},geometry:{type:'Polygon',coordinates:[[[120.71478,24.06888],[120.71540,24.06878],[120.71555,24.06935],[120.71490,24.06946],[120.71478,24.06888]]]}}]};
  const TARGET_OSM_ID = DATA.meta.osmWayId;
  const CAMPUS_CENTER = DATA.meta.campusCenter;
  const BUILDING_CENTER = DATA.meta.buildingCenter;
  const bbox = {s:24.0662,w:120.7110,n:24.0718,e:120.7185};

  const state = { mode:'campus', floor:5, room:null, map:null, pitch3d:true, labels:[], buildings:FALLBACK, liveOSM:false };
  const $ = (sel, root=document) => root.querySelector(sel);
  const $$ = (sel, root=document) => [...root.querySelectorAll(sel)];

  const campusView = $('#campusView');
  const buildingView = $('#buildingView');
  const campusNav = $('#campusNav');
  const buildingNav = $('#buildingNav');
  const floorPlan = $('#floorPlan');
  const detailDrawer = $('#detailDrawer');
  const tooltip = document.createElement('div'); tooltip.className='map-tooltip'; document.body.appendChild(tooltip);

  function setMode(mode){state.mode=mode;campusView.classList.toggle('active',mode==='campus');buildingView.classList.toggle('active',mode==='building');campusNav.classList.toggle('active',mode==='campus');buildingNav.classList.toggle('active',mode==='building');if(mode==='building')renderFloor(state.floor);setTimeout(()=>state.map?.resize(),280);}
  function roomSourceUrl(room){ return DATA.meta.sources[room.source] || DATA.meta.sources.labs; }
  function typeLabel(type){ return ({lab:'實驗室',office:'辦公室',seminar:'研討室',meeting:'會議室'})[type] || type; }

  function renderFloorButtons(){const wrap=$('#floorButtons');wrap.innerHTML='';Object.entries(DATA.floors).sort((a,b)=>Number(b[0])-Number(a[0])).forEach(([f,info])=>{const btn=document.createElement('button');btn.className='floor-btn'+(Number(f)===state.floor?' active':'');btn.disabled=!info.enabled;btn.innerHTML=`<span><strong>${info.label}</strong><small>${info.title}</small></span><span>${info.enabled?'›':'—'}</span>`;if(info.enabled)btn.addEventListener('click',()=>{state.room=null;renderFloor(Number(f));});wrap.appendChild(btn);});}
  function renderBuildingStack(){const wrap=$('#buildingStack');wrap.innerHTML='';Object.entries(DATA.floors).sort((a,b)=>Number(a[0])-Number(b[0])).forEach(([f,info],i)=>{const el=document.createElement('button');el.className='stack-floor'+(info.enabled?' enabled':'')+(Number(f)===state.floor?' active':'');el.style.bottom=`${i*22}px`;el.style.right=`${i*3}px`;el.disabled=!info.enabled;el.innerHTML=`<span>${info.label}</span><span>${info.enabled?'IEM':'CYUT'}</span>`;if(info.enabled)el.addEventListener('click',()=>renderFloor(Number(f)));wrap.appendChild(el);});}
  function renderFloor(floor){state.floor=floor;state.room=null;renderFloorButtons();renderBuildingStack();const info=DATA.floors[String(floor)];$('#floorEyebrow').textContent=`${info.label} · IEM`;$('#floorTitle').textContent=info.title;$('#floorSubtitle').textContent=info.subtitle||info.note||'';floorPlan.innerHTML='';const geom=DATA.floorGeometry[String(floor)];if(!geom)return;(geom.corridors||[]).forEach(g=>{const d=document.createElement('div');d.className='corridor';position(d,g);floorPlan.appendChild(d);});(geom.utilities||[]).forEach(g=>{const d=document.createElement('div');d.className='utility';d.textContent=g.label;position(d,g);floorPlan.appendChild(d);});(geom.labels||[]).forEach(g=>{const d=document.createElement('div');d.className='plan-label';d.textContent=g.text;d.style.left=g.x+'%';d.style.top=g.y+'%';floorPlan.appendChild(d);});Object.entries(geom.rooms).forEach(([id,g])=>{const room=DATA.rooms[id];if(!room)return;const b=document.createElement('button');b.className=`room-node ${room.type}`;b.dataset.room=id;position(b,g);b.innerHTML=`<div class="code">${room.code}</div><div class="room-name">${room.name}</div><div class="room-en">${room.en}</div>`;b.addEventListener('click',()=>selectRoom(id));floorPlan.appendChild(b);});clearDetail();}
  function position(el,g){el.style.left=g.x+'%';el.style.top=g.y+'%';el.style.width=g.w+'%';el.style.height=g.h+'%';}
  function selectRoom(id,equipmentName=''){const room=DATA.rooms[id];if(!room)return;if(state.mode!=='building')setMode('building');if(state.floor!==room.floor)renderFloor(room.floor);state.room=id;$$('.room-node').forEach(x=>x.classList.toggle('active',x.dataset.room===id));const source=roomSourceUrl(room);$('#detailEmpty').hidden=true;const c=$('#detailContent');c.hidden=false;c.innerHTML=`<div class="detail-head"><div><div class="detail-code">${room.code}</div><h3>${room.name}</h3><div class="detail-en">${room.en}</div></div><span class="type-pill">${typeLabel(room.type)}</span></div><div class="detail-desc">${room.description}</div><div class="section-title">EQUIPMENT / CAPABILITIES</div><div class="equip-list">${room.equipment.map(e=>`<div class="equip-card" ${equipmentName&&e.name.includes(equipmentName)?'style="outline:1px solid rgba(69,220,255,.6)"':''}><strong>${e.name}</strong><span>${e.kind}</span></div>`).join('')}</div><div class="section-title">RESEARCH / TEACHING</div><div class="tag-list">${room.research.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="source-box"><span>資料：朝陽工管系官方頁面／樓層配置</span><a href="${source}" target="_blank" rel="noreferrer">來源 ↗</a></div><div class="drawer-actions"><button class="secondary" data-close-detail>關閉</button><a class="primary" href="${source}" target="_blank" rel="noreferrer">官方資料</a></div>`;$('[data-close-detail]',c)?.addEventListener('click',clearDetail);detailDrawer.classList.add('open');updateBreadcrumb(room);}
  function clearDetail(){state.room=null;$$('.room-node').forEach(x=>x.classList.remove('active'));$('#detailEmpty').hidden=false;$('#detailContent').hidden=true;$('#detailContent').innerHTML='';detailDrawer.classList.remove('open');updateBreadcrumb();}
  function updateBreadcrumb(room=null){const b=$('#breadcrumb');b.innerHTML=`<button data-action="campus">校園</button><span>/</span><strong>理工大樓</strong>${room?`<span>/</span><span>${room.floor}F</span><span>/</span><span>${room.code}</span>`:''}`;$('[data-action="campus"]',b)?.addEventListener('click',()=>setMode('campus'));}
  function buildSearchIndex(){const out=[];Object.entries(DATA.rooms).forEach(([id,r])=>{const text=[r.code,r.name,r.en,r.short,r.description,...r.research,...r.equipment.map(x=>x.name+' '+x.kind)].join(' ').toLowerCase();out.push({kind:'room',id,text,code:r.code,name:r.name,sub:`${r.floor}F · ${typeLabel(r.type)}`});r.equipment.forEach(e=>out.push({kind:'equipment',id,text:(e.name+' '+e.kind+' '+r.code+' '+r.name).toLowerCase(),code:r.code,name:e.name,sub:`${r.name} · ${r.floor}F`,equipment:e.name}));});out.push({kind:'building',id:'eng',text:'理工大樓 science engineering building industrial engineering 工管'.toLowerCase(),code:'E',name:'理工大樓',sub:'OSM way 292141618 · 7F'});return out;}
  const searchIndex=buildSearchIndex();
  function runSearch(q){const box=$('#searchResults');q=q.trim().toLowerCase();if(!q){box.hidden=true;box.innerHTML='';return;}const tokens=q.split(/\s+/).filter(Boolean);const results=searchIndex.filter(x=>tokens.every(t=>x.text.includes(t))).slice(0,14);box.hidden=false;box.innerHTML=results.length?results.map((r,i)=>`<button class="search-item" data-search-i="${i}"><span class="search-code">${r.code}</span><span class="search-name"><strong>${r.name}</strong><small>${r.sub}</small></span><span class="search-kind">${r.kind==='equipment'?'設備':r.kind==='building'?'建物':'空間'}</span></button>`).join(''):'<div class="search-none">找不到相符空間或設備</div>';$$('[data-search-i]',box).forEach(el=>el.addEventListener('click',()=>activateSearchResult(results[Number(el.dataset.searchI)])));}
  function activateSearchResult(r){$('#searchResults').hidden=true;$('#searchInput').blur();if(r.kind==='building'){focusScienceBuilding();return;}setMode('building');selectRoom(r.id,r.equipment||'');}
  function setMapStatus(mode,text){const dot=$('#mapStatus .status-dot');dot.className='status-dot '+mode;$('#mapStatusText').textContent=text;}
  function parseOverpass(json){const features=[];for(const el of json.elements||[]){if(el.type!=='way'||!el.tags?.building||!Array.isArray(el.geometry)||el.geometry.length<3)continue;const coordinates=el.geometry.map(p=>[p.lon,p.lat]);if(coordinates[0][0]!==coordinates.at(-1)[0]||coordinates[0][1]!==coordinates.at(-1)[1])coordinates.push(coordinates[0]);let levels=parseFloat(el.tags['building:levels']);if(!Number.isFinite(levels))levels=null;let height=parseFloat(String(el.tags.height||'').replace(/[^0-9.]/g,''));if(!Number.isFinite(height))height=(levels||3)*3.6;features.push({type:'Feature',properties:{osm_id:el.id,name:el.tags.name||el.tags['name:zh']||'',building:el.tags.building,levels:levels||'',height,source_status:'live OSM'},geometry:{type:'Polygon',coordinates:[coordinates]}});}return {type:'FeatureCollection',features};}
  async function fetchOSMBuildings(){const q=`[out:json][timeout:25];way["building"](${bbox.s},${bbox.w},${bbox.n},${bbox.e});out tags geom;`;const endpoints=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'];for(const ep of endpoints){try{const controller=new AbortController();const t=setTimeout(()=>controller.abort(),10000);const res=await fetch(ep+'?data='+encodeURIComponent(q),{signal:controller.signal,headers:{'Accept':'application/json'}});clearTimeout(t);if(!res.ok)throw new Error('HTTP '+res.status);const geo=parseOverpass(await res.json());if(geo.features.length<3)throw new Error('Too few building features');return geo;}catch(err){console.warn('OSM endpoint failed',ep,err);}}return null;}
  function mapStyle(){return {version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm-base',type:'raster',source:'osm',paint:{'raster-saturation':-0.55,'raster-brightness-min':0.13,'raster-brightness-max':0.72,'raster-contrast':0.16}}]};}
  function initMap(){if(!window.maplibregl||!maplibregl.supported()){$('#mapFallback').hidden=false;setMapStatus('fallback','WebGL 不可用；已切換室內導覽');return;}const map=new maplibregl.Map({container:'map',style:mapStyle(),center:CAMPUS_CENTER,zoom:16.35,pitch:56,bearing:-22,antialias:true,maxPitch:78});state.map=map;map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),'bottom-right');map.on('load',async()=>{addBuildingLayers(FALLBACK);focusScienceBuilding(false);const live=await fetchOSMBuildings();if(live){state.buildings=live;state.liveOSM=true;updateBuildingSource(live);setMapStatus('online',`OpenStreetMap 已同步 · ${live.features.length} 棟建物`);}else{setMapStatus('fallback','OSM 即時同步暫不可用 · 使用備援理工大樓 footprint');}});map.on('mousemove','cyut-buildings',e=>{map.getCanvas().style.cursor='pointer';const f=e.features?.[0];if(!f)return;tooltip.style.display='block';tooltip.style.left=e.originalEvent.clientX+'px';tooltip.style.top=e.originalEvent.clientY+'px';tooltip.textContent=f.properties.name||`OSM building ${f.properties.osm_id}`;});map.on('mouseleave','cyut-buildings',()=>{map.getCanvas().style.cursor='';tooltip.style.display='none';});map.on('click','cyut-buildings',e=>{const f=e.features?.[0];if(!f)return;if(Number(f.properties.osm_id)===TARGET_OSM_ID){focusScienceBuilding();}else{const coords=e.lngLat;new maplibregl.Popup({offset:12,closeButton:false}).setLngLat(coords).setHTML(`<strong style="font-size:12px">${f.properties.name||'CYUT Building'}</strong><div style="font-size:10px;color:#62788a;margin-top:4px">OSM way ${f.properties.osm_id}${f.properties.levels?' · '+f.properties.levels+'F':''}</div>`).addTo(map);}});}
  function addBuildingLayers(geo){const map=state.map;if(!map)return;map.addSource('cyut-buildings',{type:'geojson',data:geo});map.addLayer({id:'cyut-buildings',type:'fill-extrusion',source:'cyut-buildings',minzoom:14.7,paint:{'fill-extrusion-color':['case',['==',['get','osm_id'],TARGET_OSM_ID],'#45dcff',['has','name'],'#496b80','#344f62'],'fill-extrusion-height':['coalesce',['get','height'],12],'fill-extrusion-base':0,'fill-extrusion-opacity':['case',['==',['get','osm_id'],TARGET_OSM_ID],0.94,0.73]}});map.addLayer({id:'cyut-building-outline',type:'line',source:'cyut-buildings',paint:{'line-color':['case',['==',['get','osm_id'],TARGET_OSM_ID],'#f0c15f','#7895a8'],'line-width':['case',['==',['get','osm_id'],TARGET_OSM_ID],2.6,0.7],'line-opacity':0.85}});rebuildLabels(geo);}
  function updateBuildingSource(geo){const src=state.map?.getSource('cyut-buildings');if(src)src.setData(geo);rebuildLabels(geo);}
  function centroid(feature){const ring=feature.geometry?.coordinates?.[0]||[];if(!ring.length)return null;let x=0,y=0;ring.forEach(p=>{x+=p[0];y+=p[1]});return [x/ring.length,y/ring.length];}
  function rebuildLabels(geo){state.labels.forEach(m=>m.remove());state.labels=[];if(!state.map)return;const named=geo.features.filter(f=>f.properties.name).slice(0,35);named.forEach(f=>{const c=centroid(f);if(!c)return;const el=document.createElement('div');el.className='osm-label'+(Number(f.properties.osm_id)===TARGET_OSM_ID?' target':'');el.textContent=f.properties.name;const m=new maplibregl.Marker({element:el,anchor:'center'}).setLngLat(c).addTo(state.map);state.labels.push(m);});if(!named.some(f=>Number(f.properties.osm_id)===TARGET_OSM_ID)){const el=document.createElement('div');el.className='osm-label target';el.textContent='理工大樓 · IEM';state.labels.push(new maplibregl.Marker({element:el}).setLngLat(BUILDING_CENTER).addTo(state.map));}}
  function focusScienceBuilding(openCard=true){if(state.mode!=='campus')setMode('campus');state.map?.flyTo({center:BUILDING_CENTER,zoom:18.15,pitch:64,bearing:-31,duration:900});if(openCard)$('#buildingCard').animate?.([{transform:'translateY(5px)',opacity:.5},{transform:'translateY(0)',opacity:1}],{duration:250});}
  $$('[data-action="enter-building"]').forEach(b=>b.addEventListener('click',()=>{state.floor=5;setMode('building')}));
  $('#brandHome').addEventListener('click',()=>setMode('campus'));campusNav.addEventListener('click',()=>setMode('campus'));buildingNav.addEventListener('click',()=>setMode('building'));$('#backCampus').addEventListener('click',()=>setMode('campus'));$('#searchInput').addEventListener('input',e=>runSearch(e.target.value));$('#clearSearch').addEventListener('click',()=>{$('#searchInput').value='';runSearch('');$('#searchInput').focus()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){runSearch('');$('#searchResults').hidden=true;if(state.room)clearDetail();}});$$('[data-quick]').forEach(b=>b.addEventListener('click',()=>{const q=b.dataset.quick;if(q==='office')selectRoom('e508');else if(q==='human')selectRoom('e619');else{setMode('building');renderFloor(6);}}));$('#resetMap').addEventListener('click',()=>state.map?.flyTo({center:CAMPUS_CENTER,zoom:16.35,pitch:56,bearing:-22,duration:650}));$('#togglePitch').addEventListener('click',()=>{state.pitch3d=!state.pitch3d;state.map?.easeTo({pitch:state.pitch3d?56:0,bearing:state.pitch3d?-22:0,duration:550});$('#togglePitch').textContent=state.pitch3d?'3D':'2D';});
  renderFloorButtons();renderBuildingStack();renderFloor(5);initMap();
})();
