(()=>{'use strict';
const DATA=window.IEM_DATA;
const COLORS={cyan:[.20,.84,.98],blue:[.20,.34,.44],gold:[.95,.70,.28],office:[.26,.48,.68],lab:[.18,.66,.74],seminar:[.48,.36,.70],meeting:[.70,.50,.26],utility:[.27,.32,.36],corridor:[.12,.18,.22],ground:[.035,.075,.105]};
const campusBuildings=[
{id:'E',name:'理工大樓',x:0,z:0,w:54,d:28,h:34,color:COLORS.cyan,target:true},
{id:'T',name:'教學大樓',x:-62,z:-19,w:38,d:28,h:29,color:COLORS.blue},
{id:'M',name:'管理大樓',x:-58,z:37,w:42,d:25,h:31,color:[.22,.36,.46]},
{id:'D',name:'設計大樓',x:50,z:39,w:39,d:29,h:33,color:[.23,.37,.48]},
{id:'I',name:'資訊大樓',x:59,z:-29,w:31,d:26,h:30,color:[.18,.33,.43]},
{id:'H',name:'人文與科技大樓',x:13,z:59,w:41,d:22,h:25,color:[.25,.38,.46]},
{id:'L',name:'圖書館',x:-12,z:-59,w:46,d:25,h:27,color:[.20,.35,.44]},
{id:'A',name:'行政大樓',x:-78,z:57,w:30,d:22,h:21,color:[.21,.34,.42]},
{id:'G',name:'體育館',x:78,z:57,w:39,d:32,h:18,color:[.24,.35,.41]}];
function M(){return new Float32Array(16)}function I(){const o=M();o[0]=o[5]=o[10]=o[15]=1;return o}
function mul(a,b){const o=M();for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}
function persp(fovy,aspect,n,f){const t=1/Math.tan(fovy/2),o=M();o[0]=t/aspect;o[5]=t;o[10]=(f+n)/(n-f);o[11]=-1;o[14]=2*f*n/(n-f);return o}
const sub=(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]],dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
function norm(v){const l=Math.hypot(...v)||1;return v.map(x=>x/l)}function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}
function look(eye,center){const z=norm(sub(eye,center)),x=norm(cross([0,1,0],z)),y=cross(z,x),o=I();o[0]=x[0];o[1]=y[0];o[2]=z[0];o[4]=x[1];o[5]=y[1];o[6]=z[1];o[8]=x[2];o[9]=y[2];o[10]=z[2];o[12]=-dot(x,eye);o[13]=-dot(y,eye);o[14]=-dot(z,eye);return o}
function model(x,y,z,sx,sy,sz){const o=I();o[0]=sx;o[5]=sy;o[10]=sz;o[12]=x;o[13]=y;o[14]=z;return o}
function tx(m,v){const[x,y,z,w=1]=v;return[m[0]*x+m[4]*y+m[8]*z+m[12]*w,m[1]*x+m[5]*y+m[9]*z+m[13]*w,m[2]*x+m[6]*y+m[10]*z+m[14]*w,m[3]*x+m[7]*y+m[11]*z+m[15]*w]}
const V=new Float32Array([-.5,-.5,.5,0,0,1,.5,-.5,.5,0,0,1,.5,.5,.5,0,0,1,-.5,-.5,.5,0,0,1,.5,.5,.5,0,0,1,-.5,.5,.5,0,0,1,.5,-.5,-.5,0,0,-1,-.5,-.5,-.5,0,0,-1,-.5,.5,-.5,0,0,-1,.5,-.5,-.5,0,0,-1,-.5,.5,-.5,0,0,-1,.5,.5,-.5,0,0,-1,-.5,-.5,-.5,-1,0,0,-.5,-.5,.5,-1,0,0,-.5,.5,.5,-1,0,0,-.5,-.5,-.5,-1,0,0,-.5,.5,.5,-1,0,0,-.5,.5,-.5,-1,0,0,.5,-.5,.5,1,0,0,.5,-.5,-.5,1,0,0,.5,.5,-.5,1,0,0,.5,-.5,.5,1,0,0,.5,.5,-.5,1,0,0,.5,.5,.5,1,0,0,-.5,.5,.5,0,1,0,.5,.5,.5,0,1,0,.5,.5,-.5,0,1,0,-.5,.5,.5,0,1,0,.5,.5,-.5,0,1,0,-.5,.5,-.5,0,1,0,-.5,-.5,-.5,0,-1,0,.5,-.5,-.5,0,-1,0,.5,-.5,.5,0,-1,0,-.5,-.5,-.5,0,-1,0,.5,-.5,.5,0,-1,0,-.5,-.5,.5,0,-1,0]);
class Renderer{constructor(canvas,labels){this.canvas=canvas;this.labelsRoot=labels;this.objects=[];this.labels=[];this.hot=[];this.auto=false;this.drag=false;this.moved=false;this.last=[0,0];this.cam={yaw:.75,pitch:.52,dist:170,target:[0,10,0],gyaw:.75,gpitch:.52,gdist:170,gtarget:[0,10,0]};this.gl=canvas.getContext('webgl',{antialias:true,alpha:true});if(!this.gl){canvas.insertAdjacentHTML('afterend','<div style="position:absolute;inset:0;display:grid;place-content:center;color:#9fb7c5">此瀏覽器未啟用 WebGL</div>');return}this.init();this.bind();this.resize();addEventListener('resize',()=>this.resize());requestAnimationFrame(t=>this.frame(t))}
init(){const g=this.gl,vs='attribute vec3 p;attribute vec3 n;uniform mat4 mvp;uniform mat4 mm;varying vec3 vn;void main(){gl_Position=mvp*vec4(p,1.);vn=mat3(mm)*n;}',fs='precision mediump float;varying vec3 vn;uniform vec3 c;void main(){vec3 n=normalize(vn);float d=max(dot(n,normalize(vec3(.45,.85,.35))),0.);float s=max(n.y,0.)*.16;gl_FragColor=vec4(c*(.34+.64*d+s),1.);}';const sh=(t,s)=>{const q=g.createShader(t);g.shaderSource(q,s);g.compileShader(q);return q},p=g.createProgram();g.attachShader(p,sh(g.VERTEX_SHADER,vs));g.attachShader(p,sh(g.FRAGMENT_SHADER,fs));g.linkProgram(p);this.p=p;this.ap=g.getAttribLocation(p,'p');this.an=g.getAttribLocation(p,'n');this.umvp=g.getUniformLocation(p,'mvp');this.umm=g.getUniformLocation(p,'mm');this.uc=g.getUniformLocation(p,'c');this.buf=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,this.buf);g.bufferData(g.ARRAY_BUFFER,V,g.STATIC_DRAW);g.enable(g.DEPTH_TEST);g.enable(g.CULL_FACE)}
bind(){const c=this.canvas;c.addEventListener('pointerdown',e=>{this.drag=true;this.moved=false;this.last=[e.clientX,e.clientY];c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!this.drag)return;const dx=e.clientX-this.last[0],dy=e.clientY-this.last[1];if(Math.abs(dx)+Math.abs(dy)>2)this.moved=true;this.cam.gyaw+=dx*.006;this.cam.gpitch=Math.max(.08,Math.min(1.28,this.cam.gpitch+dy*.005));this.last=[e.clientX,e.clientY]});c.addEventListener('pointerup',e=>{if(!this.moved)this.pick(e.clientX,e.clientY);this.drag=false});c.addEventListener('wheel',e=>{e.preventDefault();this.cam.gdist=Math.max(20,Math.min(260,this.cam.gdist*Math.exp(e.deltaY*.0011)))},{passive:false})}
resize(){const d=Math.min(devicePixelRatio||1,2),r=this.canvas.getBoundingClientRect();this.canvas.width=Math.max(1,Math.round(r.width*d));this.canvas.height=Math.max(1,Math.round(r.height*d));if(this.gl)this.gl.viewport(0,0,this.canvas.width,this.canvas.height)}
setObjects(o){this.objects=o;this.labelsRoot.innerHTML='';this.labels=[];o.filter(x=>x.label).forEach(x=>{const e=document.createElement('button');e.className='scene-label'+(x.target?' target':'')+(x.selected?' selected':'');e.textContent=x.label;e.onclick=()=>x.onClick?.();this.labelsRoot.appendChild(e);this.labels.push({o:x,e})})}
setHot(list,root){root.innerHTML='';this.hot=[];list.forEach(h=>{const e=document.createElement('div');e.className='hotspot';e.innerHTML=`<div class="pulse"></div><div class="hotlabel">${h.label}</div>`;e.onclick=()=>h.onClick?.();root.appendChild(e);this.hot.push({h,e})})}
setCamera(y,p,d,t){Object.assign(this.cam,{gyaw:y,gpitch:p,gdist:d,gtarget:[...t]})}
project(p){const q=tx(this.vp,[...p,1]);if(q[3]<=0)return null;const r=this.canvas.getBoundingClientRect();return[(q[0]/q[3]*.5+.5)*r.width,(-q[1]/q[3]*.5+.5)*r.height,q[2]/q[3]]}
pick(cx,cy){const r=this.canvas.getBoundingClientRect(),x=cx-r.left,y=cy-r.top;let best=null,bd=1e9;this.objects.filter(o=>o.pickable).forEach(o=>{const p=this.project([o.x,o.y+Math.max(o.h,1),o.z]);if(!p)return;const d=Math.hypot(p[0]-x,p[1]-y);if(d<65&&d<bd){best=o;bd=d}});best?.onClick?.()}
frame(){if(!this.gl)return;const c=this.cam;if(this.auto&&!this.drag)c.gyaw+=.0014;c.yaw+=(c.gyaw-c.yaw)*.08;c.pitch+=(c.gpitch-c.pitch)*.08;c.dist+=(c.gdist-c.dist)*.08;for(let i=0;i<3;i++)c.target[i]+=(c.gtarget[i]-c.target[i])*.08;const cp=Math.cos(c.pitch),eye=[c.target[0]+c.dist*cp*Math.sin(c.yaw),c.target[1]+c.dist*Math.sin(c.pitch),c.target[2]+c.dist*cp*Math.cos(c.yaw)],pr=persp(Math.PI/4,this.canvas.width/this.canvas.height,.1,800);this.vp=mul(pr,look(eye,c.target));this.draw();this.labels.forEach(v=>{const p=this.project([v.o.x,v.o.labelY??(v.o.y+v.o.h+2),v.o.z]);v.e.style.display=p&&p[2]<1?'block':'none';if(p){v.e.style.left=p[0]+'px';v.e.style.top=p[1]+'px'}});this.hot.forEach(v=>{const p=this.project(v.h.pos);v.e.style.display=p&&p[2]<1?'block':'none';if(p){v.e.style.left=p[0]+'px';v.e.style.top=p[1]+'px'}});requestAnimationFrame(()=>this.frame())}
draw(){const g=this.gl;g.clearColor(.018,.045,.07,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.useProgram(this.p);g.bindBuffer(g.ARRAY_BUFFER,this.buf);g.enableVertexAttribArray(this.ap);g.enableVertexAttribArray(this.an);g.vertexAttribPointer(this.ap,3,g.FLOAT,false,24,0);g.vertexAttribPointer(this.an,3,g.FLOAT,false,24,12);this.objects.forEach(o=>{const mm=model(o.x,o.y+o.h/2,o.z,o.w,o.h,o.d),mvp=mul(this.vp,mm);g.uniformMatrix4fv(this.umvp,false,mvp);g.uniformMatrix4fv(this.umm,false,mm);g.uniform3fv(this.uc,o.color||COLORS.blue);g.drawArrays(g.TRIANGLES,0,36)})}}
const cv=document.getElementById('campusView'),iv=document.getElementById('indoorView'),ct=document.getElementById('campusTab'),it=document.getElementById('indoorTab');const cr=new Renderer(document.getElementById('campusCanvas'),document.getElementById('campusLabels')),ir=new Renderer(document.getElementById('indoorCanvas'),document.getElementById('indoorLabels'));let floor=6,selected=null,walk=false;
function mode(m){cv.classList.toggle('active',m==='c');iv.classList.toggle('active',m==='i');ct.classList.toggle('active',m==='c');it.classList.toggle('active',m==='i');setTimeout(()=>{cr.resize();ir.resize()},350)}
function campus(){const o=[{x:0,y:-1,z:0,w:220,d:170,h:2,color:COLORS.ground}];campusBuildings.forEach(b=>o.push({...b,y:0,label:b.name,pickable:true,onClick:()=>focusBuilding(b)}));cr.setObjects(o);cr.setCamera(.78,.5,180,[0,10,0])}function focusBuilding(b){cr.setCamera(.78,.42,b.target?105:125,[b.x,b.h*.35,b.z])}
function enter(){mode('i');renderFloor(floor);ir.setCamera(.82,.62,112,[0,0,0])}
function rw(g){const s=.82;return{x:(g.x+g.w/2-50)*s,z:(g.y+g.h/2-50)*s,w:g.w*s,d:g.h*s}}
function typeColor(t){return COLORS[t]||COLORS.lab}
function buildIndoor(f,sel=null){const g=DATA.floorGeometry[String(f)],o=[{x:0,y:-.45,z:0,w:90,d:76,h:.9,color:[.055,.11,.15]}];(g.corridors||[]).forEach(c=>{const p=rw(c);o.push({x:p.x,y:.01,z:p.z,w:p.w,d:p.d,h:.18,color:COLORS.corridor})});(g.utilities||[]).forEach(u=>{const p=rw(u);o.push({x:p.x,y:0,z:p.z,w:p.w,d:p.d,h:2.5,color:COLORS.utility,label:u.label,labelY:4.1})});Object.entries(g.rooms).forEach(([id,rg])=>{const r=DATA.rooms[id],p=rw(rg),s=id===sel,col=s?COLORS.gold:typeColor(r.type),wall=s?[.62,.46,.19]:col.map(x=>x*.72),t=.22,wh=2.75;o.push({id,x:p.x,y:.02,z:p.z,w:p.w,d:p.d,h:.16,color:col,label:`${r.code} · ${r.name}`,labelY:3.9,pickable:true,selected:s,onClick:()=>selectRoom(id)});o.push({x:p.x-p.w/2+t/2,y:.16,z:p.z,w:t,d:p.d,h:wh,color:wall},{x:p.x+p.w/2-t/2,y:.16,z:p.z,w:t,d:p.d,h:wh,color:wall},{x:p.x,y:.16,z:p.z-p.d/2+t/2,w:p.w,d:t,h:wh,color:wall});if(s)r.equipment.slice(0,4).forEach((e,i)=>{const ox=((i%2)-.5)*Math.min(p.w*.38,6),oz=(Math.floor(i/2)-.35)*Math.min(p.d*.30,5);o.push({x:p.x+ox,y:.18,z:p.z+oz,w:1.1,d:1.1,h:.65,color:COLORS.gold})})});return o}
function renderFloor(f){floor=f;selected=null;walk=false;const F=DATA.floors[String(f)];document.getElementById('floorEyebrow').textContent=`${f}F · IEM`;document.getElementById('floorTitle').textContent=F.title;document.getElementById('floorSubtitle').textContent=(F.subtitle||F.note||'')+' · 拖曳旋轉 / 滾輪縮放 / 點房間進入';floorButtons();roomRail();drawer();ir.setObjects(buildIndoor(f));ir.setHot([],document.getElementById('hotspots'));ir.setCamera(.82,.62,f===1?120:108,[0,1,0])}
function selectRoom(id){const r=DATA.rooms[id],rg=DATA.floorGeometry[String(r.floor)].rooms[id];if(r.floor!==floor)renderFloor(r.floor);selected=id;roomRail();drawer();const p=rw(rg);ir.setObjects(buildIndoor(r.floor,id));ir.setCamera(.82,walk?.18:.43,walk?31:57,[p.x,1.25,p.z]);const h=[];r.equipment.slice(0,4).forEach((e,i)=>{const ox=((i%2)-.5)*Math.min(p.w*.38,6),oz=(Math.floor(i/2)-.35)*Math.min(p.d*.30,5);h.push({label:e.name,pos:[p.x+ox,1.8,p.z+oz],onClick:()=>{document.querySelectorAll('.equip-card').forEach(x=>x.style.outline='');document.querySelector(`[data-eq="${i}"]`)?.style.setProperty('outline','1px solid rgba(242,198,109,.75)')}})});ir.setHot(h,document.getElementById('hotspots'))}
function floorButtons(){const w=document.getElementById('floorButtons');w.innerHTML='';[7,6,5,4,3,2,1].forEach(f=>{const en=[1,5,6].includes(f),F=DATA.floors[String(f)],b=document.createElement('button');b.className='floorbtn'+(f===floor?' active':'');b.disabled=!en;b.innerHTML=`<span><strong>${f}F</strong><small>${en?(F?.title||'IEM'):'CYUT'}</small></span><span>${en?'›':'—'}</span>`;if(en)b.onclick=()=>renderFloor(f);w.appendChild(b)})}
function roomRail(){const w=document.getElementById('roomRail');w.innerHTML='';Object.entries(DATA.rooms).filter(x=>x[1].floor===floor).forEach(([id,r])=>{const b=document.createElement('button');b.className='roomchip'+(id===selected?' active':'');b.innerHTML=`<strong>${r.code}</strong>${r.name}`;b.onclick=()=>selectRoom(id);w.appendChild(b)})}
function drawer(){const e=document.getElementById('drawerEmpty'),c=document.getElementById('drawerContent'),d=document.getElementById('drawer');if(!selected){e.hidden=false;c.hidden=true;d.classList.remove('open');return}const r=DATA.rooms[selected];e.hidden=true;c.hidden=false;d.classList.add('open');c.innerHTML=`<div class="drawer-code">${r.code} · ${r.floor}F</div><h2>${r.name}</h2><div class="drawer-en">${r.en}</div><div class="drawer-desc">${r.description}</div><div class="section-title">EQUIPMENT / CAPABILITY HOTSPOTS</div>${r.equipment.map((q,i)=>`<div class="equip-card" data-eq="${i}"><strong>${q.name}</strong><span>${q.kind}</span></div>`).join('')}<div class="section-title">RESEARCH / TEACHING</div><div class="tags">${r.research.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="drawer-actions"><button class="secondary" id="ovRoom">鳥瞰此空間</button><button class="primary" id="wkRoom">走入空間</button></div>`;document.getElementById('ovRoom').onclick=()=>{walk=false;selectRoom(selected)};document.getElementById('wkRoom').onclick=()=>{walk=true;selectRoom(selected)}}
function camera(w){walk=w;if(selected)selectRoom(selected);else ir.setCamera(.82,w?.2:.62,w?50:108,[0,1,0])}
const idx=[];Object.entries(DATA.rooms).forEach(([id,r])=>idx.push({id,code:r.code,name:r.name,text:[r.code,r.name,r.en,r.description,...r.research,...r.equipment.flatMap(e=>[e.name,e.kind])].join(' ').toLowerCase()}));function search(q){const box=document.getElementById('searchResults');q=q.trim().toLowerCase();if(!q){box.hidden=true;return}const res=idx.filter(x=>q.split(/\s+/).every(t=>x.text.includes(t))).slice(0,10);box.hidden=false;box.innerHTML=res.length?res.map((x,i)=>`<button class="search-item" data-i="${i}"><code>${x.code}</code><span><strong>${x.name}</strong><small>${DATA.rooms[x.id].floor}F · ${DATA.rooms[x.id].en}</small></span><em>進入</em></button>`).join(''):'<div style="padding:12px;color:#7893a3;font-size:10px">找不到相符空間或設備</div>';box.querySelectorAll('[data-i]').forEach(el=>el.onclick=()=>{const x=res[+el.dataset.i];box.hidden=true;mode('i');renderFloor(DATA.rooms[x.id].floor);setTimeout(()=>selectRoom(x.id),70)})}
document.getElementById('searchInput').oninput=e=>search(e.target.value);document.getElementById('enterBuilding').onclick=enter;ct.onclick=()=>mode('c');it.onclick=enter;document.getElementById('homeBtn').onclick=()=>mode('c');document.getElementById('backCampus').onclick=()=>mode('c');document.getElementById('resetCampus').onclick=()=>cr.setCamera(.78,.5,180,[0,10,0]);document.getElementById('orbitToggle').onclick=e=>{cr.auto=!cr.auto;e.currentTarget.textContent=cr.auto?'停止環視':'自動環視'};document.getElementById('overviewBtn').onclick=()=>camera(false);document.getElementById('walkBtn').onclick=()=>camera(true);campus();floorButtons();renderFloor(6);
})();