'use strict';
/* Runtime extensions. One world and one metre-scale physics model for desktop/XR. */
(()=>{const M=CQ.M,D=CQ.DATA,$=id=>document.getElementById(id);
function line(g,a,b,col,w=.017){g.beam(a,b,w,col,5);}
function distance(a,b){return Math.hypot(a.x-b.x,a.z-b.z);}
function visible(vp,c){let p=c.center,r=c.radius||50;if(!p)return true;for(let i=0;i<3;i++)for(let s of [-1,1]){let a=vp[3]+s*vp[i],b=vp[7]+s*vp[i+4],d=vp[11]+s*vp[i+8],e=vp[15]+s*vp[i+12];if(a*p[0]+b*p[1]+d*p[2]+e < -r*Math.hypot(a,b,d))return false;}return true;}
CQ.installAppV2=App=>{let P=App.prototype,init=P.initMeshes,bind=P.bind,drawMap=P.drawMap,oldTick=P.tick,oldXRSelect=P.xrSelect,oldMenu=P.menu;
P.initMeshes=function(){init.call(this);let c=document.createElement('canvas');c.width=c.height=4;let ctx=c.getContext('2d');ctx.fillStyle='#000';ctx.fillRect(0,0,4,4);this.blackTexture=this.r.texture(c);this.qualityName='high';this.lastPhysicsLocation=null;};
P.ensureWorld=function(){let w=this.game.world;if(w.uploaded)return;w.uploaded=true;for(let c of w.chunks){c.mesh=this.r.upload(c.geo);c.vertexCount=c.mesh.count;c.geo.v=[];if(c.lodGeo){c.lodMesh=this.r.upload(c.lodGeo);c.lodGeo.v=[];}}w.vertexCount=w.chunks.reduce((n,c)=>n+c.vertexCount,0);let cache=new Map();for(let l of [...w.labels,...w.signs]){let key=l.name+'|'+l.sub;if(!cache.has(key))cache.set(key,this.r.texture(CQ.makeText(l.name,l.sub,768,144)));l.tex=cache.get(key);}this.signTextureCount=cache.size;};
P.bind=function(){bind.call(this);$('showPerf')?.addEventListener('change',e=>{$('perf').hidden=!e.target.checked;});$('quality')?.addEventListener('change',e=>this.setQuality(e.target.value));$('exposure')?.addEventListener('input',e=>{this.r.exposure=Number(e.target.value);});$('hideLabels')?.addEventListener('change',e=>{this.hideLabels=e.target.checked;});this.game.onTeleport=()=>{this.xrNeedsAlign=true;this.xrDesiredYaw=this.xr?this.headYaw:this.game.player.yaw;this.lastRoute=-100;};};
P.menu=function(){oldMenu.call(this);if(this.xr){let d=this.game.dialog;d.options.splice(d.options.length-1,0,{label:this.qualityName==='low'?'VR 畫質：切換均衡':'VR 畫質：切換效能',action:()=>{this.setQuality(this.qualityName==='low'?'balanced':'low');this.game.close();}});this.showDialog(d);}};
P.setQuality=function(name){this.qualityName=name;if($('quality'))$('quality').value=name;this.r.quality=name==='low'?0:name==='balanced'?.55:1;this.r.pixelScale=name==='low'?.75:name==='balanced'?1:1;let size=name==='high'?2048:1024;if(this.r.shadowSize!==size)this.r.initShadow(size);this.r.lastShadow=-1e5;this.game.toast(name==='high'?'高品質：法線材質與 2048 陰影':name==='balanced'?'均衡：法線材質與 1024 陰影':'效能：基本材質、關閉陰影');};
P.desktopCamera=function(t){let g=this.game,p=g.player;if(!g.started)return{eye:[52,CQ.ground(52,124)+2.8,124],target:[5,CQ.ground(6,73)+13.8,73]};if(g.overview){let a=.65+p.yaw,r=this.orbitRadius;return{eye:[Math.sin(a)*r,175,Math.cos(a)*r-30],target:[-10,20,-40]};}let focus=[p.x,p.y+(g.cart.driving?1.85:1.66),p.z],forward=[-Math.sin(p.yaw)*Math.cos(this.pitch),Math.sin(this.pitch),-Math.cos(p.yaw)*Math.cos(this.pitch)];if(g.firstPerson)return{eye:focus,target:M.add(focus,forward)};let eye=M.sub(focus,M.scale(forward,g.cart.driving?7:4.1)),h=g.world.physics.segment(focus,eye);if(h)eye=M.add(focus,M.scale(M.sub(eye,focus),Math.max(.08,h.t-.05)));eye[1]=Math.max(eye[1],CQ.ground(eye[0],eye[2])+.3);return{eye,target:focus};};
P.buildList=function(){let root=$('buildingList');root.replaceChildren();let recover=document.createElement('button');recover.textContent='恢復目前任務導航';recover.onclick=()=>{this.game.navOverride=null;this.toggleMap(false);this.lastRoute=-100;};root.append(recover);for(let b of D.buildings){let row=document.createElement('div');row.className='buildingRow';let title=document.createElement('strong');title.textContent=(this.game.state.visited.includes(b.id)?'✓ ':'')+b.name;let sub=document.createElement('small');sub.textContent=b.enterable?`${b.floors} 個可行走樓層 · 重建層高 ${b.floorHeight} m`:'建築外部 · 不開放室內';let nav=document.createElement('button');nav.textContent='設定導航';nav.onclick=()=>{this.game.navOverride=b.id;this.toggleMap(false);this.lastRoute=-100;};let go=document.createElement('button');go.textContent='入口導覽';go.onclick=()=>{this.game.cart.driving=false;this.game.teleport(...b.door,{assist:true,kind:'map-fast-travel'});this.toggleMap(false);};row.append(title,sub,nav,go);root.append(row);}};
P.drawMap=function(canvas,full=false){let loc=this.game.location();if(full||!loc.building){drawMap.call(this,canvas,full);return;}let ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,p=this.game.player,s=7.0;ctx.fillStyle='#152823';ctx.fillRect(0,0,w,h);let xy=(x,z)=>[w/2+(x-p.x)*s,h/2+(z-p.z)*s];for(let q of this.game.world.physics.surfaces){if(q.building!==loc.building||Math.abs(q.y-p.y)>1.95)continue;ctx.fillStyle=q.kind==='stair'?'#c0a571':'#52645b';ctx.fillRect(...xy(q.x0,q.z0),q.w*s,q.d*s);}for(let q of this.game.world.physics.solids){if(p.y+.1>=q.y1||p.y+1.6<q.y0)continue;if(Math.hypot(q.x-p.x,q.z-p.z)>60)continue;ctx.fillStyle='#9aa79b';ctx.fillRect(...xy(q.x0,q.z0),Math.max(1,q.w*s),Math.max(1,q.d*s));}for(let t of this.game.interactables()){if(Math.abs(t.y-p.y)>.8)continue;let a=xy(t.x,t.z);ctx.fillStyle=t.id===this.game.objective()?.id?'#ffcb73':'#b4d5d2';ctx.beginPath();ctx.arc(...a,4,0,7);ctx.fill();}ctx.save();ctx.translate(w/2,h/2);ctx.rotate(-p.yaw);ctx.fillStyle='#fff5dd';ctx.beginPath();ctx.moveTo(0,-11);ctx.lineTo(7,8);ctx.lineTo(-7,8);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle='#e3e6db';ctx.font='21px system-ui';ctx.fillText(loc.title+' · 樓層圖',18,30);};
P.updateRoute=function(t){let g=this.game,p=g.player,target=g.objective();if(!target){this.route=null;return;}let nav=target,loc=g.location();if(target.building&&(!loc.building||loc.building!==target.building)){nav=g.targetFor(target.building);}else if(target.floor&&loc.floor!==target.floor){nav=g.world.lifts.find(q=>q.building===target.building&&q.floor===loc.floor)||target;}this.navStep=nav;let key=nav.id+':'+loc.floor;if(t-this.lastRoute<3200&&key===this.routesKey)return;this.lastRoute=t;this.routesKey=key;let geo=new CQ.G();if(loc.building){this.route=null;let a=[p.x,p.y+.2,p.z],b=[nav.x,nav.y+.2,nav.z];if(Math.abs(nav.y-p.y)<.7&&!g.world.physics.segment([p.x,p.y+1.3,p.z],[nav.x,nav.y+1.3,nav.z]))line(geo,a,b,[.71,.53,.23],.017);}else{this.route=CQ.pathfind(p,nav,g.world.boxes);if(this.route)for(let i=0;i<this.route.points.length-1;i++)geo.road(this.route.points[i],this.route.points[i+1],.085,[.82,.61,.27],.11);}this.r.update(this.routeMesh,geo);};
P.updateDynamic=function(t){let g=this.game,p=g.player,geo=new CQ.G(),target=g.objective(),near=g.nearest();for(let a of g.interactables()){if(Math.abs(a.y-p.y)>1.15||distance(a,p)>34||a.id=== 'CART')continue;let active=target?.id===a.id||this.navStep?.id===a.id,col=active?[.90,.68,.31]:[.36,.54,.48];geo.ring(a.x,a.y+.075,a.z,active?.70:.29,active?.70:.29,.045,col,24);if(active){let yy=a.y+2.15+Math.sin(t*.002)*.04;geo.cylinder(a.x,yy,a.z,.12,.25,col,6,0);}}
 for(let a of g.world.learning){if(!a.id.startsWith('ITEM')||distance(a,p)>100)continue;let i=+a.id.slice(4);if(g.state.fiveS.sorted.includes(i)||g.state.fiveS.held===i)continue;let x=a.x,y=a.y,z=a.z;if(i===0){geo.box(x,y+.10,z,.075,.06,.58,CQ.Palette.metal);geo.cylinder(x,y+.1,z-.30,.12,.065,CQ.Palette.metal,8);}else if(i===1){geo.box(x,y+.30,z,.60,.60,.50,CQ.Palette.wood);geo.box(x,y+.61,z,.03,.01,.5,[.83,.75,.56]);}else{geo.ring(x,y+.06,z,.31,.31,.045,[.13,.15,.14],25);geo.box(x+.30,y+.10,z,.1,.12,.16,[.6,.29,.18]);}}
 let sy=CQ.ground(2,188);for(let i=0;i<3;i++)geo.box(1+i*.85,sy+.4,188,.7,.8,.7,CQ.Palette.wood);
 for(let l of this.xrLines){if(l.points)for(let i=1;i<l.points.length;i++)line(geo,l.points[i-1],l.points[i],l.color,.009);else line(geo,l.a,l.b,l.color,.005);if(l.end)geo.ring(l.end[0],l.end[1]+.012,l.end[2],.22,.22,.025,l.color,16);}
 this.r.update(this.dynamic,geo);if(t-this.lastDynamic>130&&g.moving&&!g.firstPerson&&!this.xr){this.lastDynamic=t;this.r.update(this.avatarMesh,CQ.makeAvatar([.24,.30,.29],t/1000,true));}
};
P.drawWorld=function(vp,eye,t,clear=true){let r=this.r,g=this.game,p=g.player,w=g.world;this.eye=eye;r.begin(vp,eye,clear);let inside=g.location().building;for(let c of w.chunks){if(c.kind==='foliage'&&Math.hypot(c.center[0]-eye[0],c.center[2]-eye[2])>(this.xr?190:340)+c.radius)continue;if(!['terrain','ground','landscape'].includes(c.kind)&&!visible(vp,c))continue;let range=Math.hypot(c.center[0]-eye[0],c.center[2]-eye[2]);let mesh=c.lodMesh&&range>(this.xr?95:145)&&c.id!==inside?c.lodMesh:c.mesh;r.draw(mesh);}if(g.started&&this.route)r.draw(this.routeMesh);r.draw(this.dynamic);
 if(!inside||g.overview){if(Math.hypot(g.cart.x-eye[0],g.cart.z-eye[2])<160)r.draw(this.cartMesh,M.trs(g.cart.x,CQ.ground(g.cart.x,g.cart.z)+.05,g.cart.z,g.cart.yaw));if(Math.hypot(13-eye[0],203-eye[2])<110)r.draw(this.npcMesh2,M.trs(13,CQ.ground(13,203)+.05,203,.6));let pts=[[-18,-86],[81,-86],[81,-4],[-18,-4]],lens=[99,82,99,82];for(let i=0;i<6;i++){let u=(t*.0008+i*59)%362,k=0;while(u>lens[k])u-=lens[k++];let a=pts[k],b=pts[(k+1)%4],f=u/lens[k],x=a[0]+(b[0]-a[0])*f,z=a[1]+(b[1]-a[1])*f;if(Math.hypot(x-eye[0],z-eye[2])>90)continue;let y=CQ.ground(x,z)+.045;if(!w.physics.safe(x,y,z))continue;r.draw(i%2?this.npcMesh:this.npcMesh2,M.trs(x,y,z,Math.atan2(-(b[0]-a[0]),-(b[1]-a[1]))));}}
 if(g.started&&!g.firstPerson&&!this.xr&&!g.overview)r.draw(this.avatarMesh,M.trs(p.x,p.y+(g.cart.driving?.45:0),p.z,p.yaw,1,g.cart.driving?.72:1,1));
 if(g.state.fiveS.held!==null){let right=[...this.rays.entries()].find(([src])=>src.handedness==='right')?.[1],model=this.xr&&right?M.mul(right.tm,M.trs(.03,-.07,-.15)):M.mul(M.trs(p.x,p.y+1.17,p.z,p.yaw),M.trs(.31,0,-.60));r.draw(this.heldMeshes[g.state.fiveS.held],model);}
 if(!this.hideLabels){for(let l of w.signs){let d=Math.hypot(l.x-eye[0],l.y-eye[1],l.z-eye[2]);if(d>(this.xr?43:70)||d<.35)continue;if(Math.cos(l.yaw)*(eye[2]-l.z)+Math.sin(l.yaw)*(eye[0]-l.x)<-.2)continue;r.label(l.tex,M.trs(l.x,l.y,l.z,l.yaw,l.w,l.h,1));}for(let l of w.labels){let d=Math.hypot(l.x-eye[0],l.z-eye[2]);if(d>26||Math.abs(p.y-CQ.ground(l.x,l.z))>3.9||!g.started||g.overview)continue;let yaw=Math.atan2(eye[0]-l.x,eye[2]-l.z);r.label(l.tex,M.trs(l.x,l.y,l.z,yaw,l.w,l.h,1));}}
 if(this.xr){let yaw=this.headYaw,loc=M.add(this.headWorld,[-Math.sin(yaw)*1.9,-.60,-Math.cos(yaw)*1.9]);r.label(this.hudTexture,M.trs(...loc,yaw,1.12,.164,1),true);if(g.dialog&&this.panelModel)r.label(this.panelTexture,this.panelModel,true);if(performance.now()<g.fadeUntil){let pos=M.add(this.headWorld,[-Math.sin(yaw)*.35,0,-Math.cos(yaw)*.35]);r.label(this.blackTexture,M.trs(...pos,yaw,4,4,1),true);}}
};
P.tick=function(t,dt){this.game.step(dt);oldTick.call(this,t,dt);let loc=this.game.location(),p=this.game.player,tar=this.game.objective();$('zone').textContent=loc.title;$('maploc').textContent=loc.title;$('coord').textContent=p.y.toFixed(1)+' m';$('floorHud').textContent=loc.floor?loc.floor+'F':'OUTDOOR';$('heightHud').textContent='模型標高 '+p.y.toFixed(2)+' m';$('nextTarget').textContent=tar?`下一站：${tar.name} · ${Math.round(distance(p,tar))} m${Math.abs(tar.y-p.y)>1?' / 高差 '+(tar.y-p.y>0?'+':'')+(tar.y-p.y).toFixed(1)+' m':''}`:'今日任務已完成。';$('fade').style.opacity=performance.now()<this.game.fadeUntil?'1':'0';if(loc.title!==this.lastPhysicsLocation&&this.game.started){this.lastPhysicsLocation=loc.title;this.game.log('zone_entered',{zone:loc.title,x:p.x,y:p.y,z:p.z});}
 if(!this.xr||!this.game.liftPending)this.r.updateShadow(this.game.world.chunks,[p.x,p.y+4,p.z],t,this.game.overview||!this.game.started);
};
P.rig=function(){let p=this.game.player;return M.trs(p.x,p.y,p.z,p.yaw);};
P.arc=function(ray){return this.game.world.physics.arc(ray.o,ray.d,this.game.player);};
P.xrSelect=function(source){if(this.game.dialog)return oldXRSelect.call(this,source);let ray=this.rays.get(source);if(!ray)return;let best=null,score=Infinity,p=this.game.player;for(let t of this.game.interactables()){if(Math.abs(t.y-p.y)>.92||distance(p,t)>4.3)continue;let v=M.sub([t.x,t.y+1.1,t.z],ray.o),proj=M.dot(v,ray.d),side=Math.hypot(...M.sub(v,M.scale(ray.d,proj)));if(proj>0&&proj<score&&side<.9){best=t;score=proj;}}if(best)this.game.interact(best.id);else{let n=this.game.nearest();if(n)this.game.interact(n.id);else this.game.toast('先到正確樓層，靠近標記後用右扳機互動。');}if(this.game.dialog){this.placePanel();this.panelYaw=this.headYaw;}};
P.drawPanel=function(){let ctx=this.panelCanvas.getContext('2d'),d=this.game.dialog;if(!d)return;ctx.clearRect(0,0,1024,1024);ctx.fillStyle='#122920';ctx.beginPath();ctx.roundRect(0,0,1024,1024,26);ctx.fill();ctx.strokeStyle='#b5a579';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#c9b681';ctx.font='22px system-ui';ctx.fillText('CYUT CAMPUS QUEST / 學生平板',44,51);ctx.fillStyle='#f3f1e7';ctx.font='bold 38px system-ui';ctx.fillText(d.title,44,112,930);let n=d.options.length,rh=n>8?61:n>6?69:82,start=974-n*rh,lines=[];ctx.font='27px system-ui';for(let para of d.body.split('\n')){let line='';for(let c of para){if(ctx.measureText(line+c).width>930){lines.push(line);line='';}line+=c;}lines.push(line);}ctx.fillStyle='#c7d1c7';let max=Math.floor((start-153)/36);lines.slice(0,max).forEach((v,i)=>ctx.fillText(v,44,157+i*36));this.panelRects=[];d.options.forEach((o,i)=>{let y=start+i*rh,h=rh-10;ctx.fillStyle=i===0?'#34473a':'#24382f';ctx.beginPath();ctx.roundRect(34,y,956,h,9);ctx.fill();ctx.font=(n>8?'25':'28')+'px system-ui';ctx.fillStyle='#f0eee3';ctx.fillText(o.label,56,y+h/2+9,915);this.panelRects.push({x:34,y,w:956,h,index:i});});this.r.updateTexture(this.panelTexture,this.panelCanvas);};
};
})();
