'use strict';
(()=>{
const $=id=>document.getElementById(id),M=CQ.M;
function fatal(e){console.error(e);$('boot').hidden=true;$('fatal').hidden=false;$('fatalText').textContent=String(e.message||e);}
window.addEventListener('error',e=>{if(!window.CampusQuest)fatal(e.error||e.message);});
function wrap(ctx,text,maxWidth){let out=[];for(let p of String(text).split('\n')){let line='';for(const c of p){if(ctx.measureText(line+c).width>maxWidth&&line){out.push(line);line=c;}else line+=c;}out.push(line);}return out;}
function beam(g,a,b,col,width=.012){let d=M.norm(M.sub(b,a)),r=M.norm(M.cross(d,Math.abs(d[1])>.9?[1,0,0]:[0,1,0])),u=M.cross(d,r),v=(p,s,t)=>M.add(p,M.add(M.scale(r,s*width),M.scale(u,t*width)));g.quad(v(a,-1,0),v(b,-1,0),v(b,1,0),v(a,1,0),col);g.quad(v(a,0,-1),v(b,0,-1),v(b,0,1),v(a,0,1),col);}
class App{
 constructor(){this.r=new CQ.Renderer($('scene'));this.game=new CQ.Game();this.keys=new Set();this.pitch=-.18;this.drag=false;this.orbit=0;this.orbitRadius=365;this.mapOpen=false;this.xr=null;this.xrSpace=null;this.xrBusy=false;this.smoothVR=false;this.xrNeedsAlign=true;this.xrDesiredYaw=0;this.headYaw=0;this.headLocal=[0,1.65,0];this.rays=new Map();this.buttons=new Map();this.teleports=new Map();this.panelModel=null;this.panelRects=[];this.lastDynamic=0;this.lastRoute=-100;this.lastHUD=0;this.lastTick=performance.now();this.playClock=null;this.stats={frames:0,start:performance.now(),fps:0};this.route=null;this.routesKey='';this.eye=[0,0,0];this.xrLines=[];this.lastWorld='campus';this.initMeshes();this.bind();this.refresh();this.ensureWorld();$('boot').hidden=true;this.capabilities();requestAnimationFrame(t=>this.frame(t));}
 initMeshes(){this.avatarMesh=this.r.upload(CQ.makeAvatar(),true);this.npcMesh=this.r.upload(CQ.makeAvatar([.46,.48,.41]));this.npcMesh2=this.r.upload(CQ.makeAvatar([.55,.39,.29]));this.cartMesh=this.r.upload(CQ.makeCart());this.dynamic=this.r.upload(new CQ.G(),true);this.routeMesh=this.r.upload(new CQ.G(),true);this.heldMeshes=[0,1,2].map(i=>{let a=new CQ.G();if(i===0){a.box(0,0,0,.07,.06,.40,[.72,.75,.74]);a.cylinder(0,.005,-.23,.1,.05,[.72,.75,.74],6);}else if(i===1){a.box(0,0,0,.28,.28,.28,[.65,.49,.30]);}else a.ring(0,0,0,.18,.18,.035,[.21,.24,.25],16);return this.r.upload(a);});this.hudCanvas=CQ.makeText('朝陽校園探索','左握把傳送 · 右扳機互動');this.hudTexture=this.r.texture(this.hudCanvas);this.panelCanvas=document.createElement('canvas');this.panelCanvas.width=1024;this.panelCanvas.height=1024;this.panelTexture=this.r.texture(this.panelCanvas);}
 ensureWorld(){const w=this.game.world;if(!w.mesh){w.mesh=this.r.upload(w.geo);for(const l of w.labels)l.tex=this.r.texture(CQ.makeText(l.name,l.sub));}if(this.lastWorld!==w.key){this.lastWorld=w.key;this.xrDesiredYaw=this.game.player.yaw;this.xrNeedsAlign=true;this.route=null;this.lastRoute=-100;}}
 bind(){let g=this.game;g.onChange=()=>this.refresh();g.onToast=s=>{$('toast').textContent=s;$('toast').hidden=false;this.updateXRHud();};g.onDialog=d=>this.showDialog(d);g.onTeleport=()=>{this.xrNeedsAlign=true;this.xrDesiredYaw=this.headYaw;};
 $('start').onclick=()=>this.start();$('vrLanding').onclick=()=>this.enterVR();$('vrBtn').onclick=()=>this.xr?this.xr.end():this.enterVR();$('menuBtn').onclick=()=>this.menu();$('mapBtn').onclick=()=>this.toggleMap();$('mapClose').onclick=()=>this.toggleMap(false);$('viewBtn').onclick=()=>{g.firstPerson=!g.firstPerson;g.overview=false;this.refresh();};$('recordsBtn').onclick=()=>{$('settings').hidden=false;document.exitPointerLock?.();};$('settingsClose').onclick=()=>{$('settings').hidden=true;};$('jsonExport').onclick=()=>g.export('json');$('csvExport').onclick=()=>g.export('csv');$('resetBtn').onclick=()=>{g.open('重置本機進度','這會清除所有任務進度與事件紀錄；無法復原。',[{label:'確認重置',action:()=>{g.reset();g.close();this.refresh();}}]);$('settings').hidden=true;};
 document.addEventListener('keydown',e=>{if(['Tab','Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(!g.started||this.xr)return;this.keys.add(e.code);if(e.repeat)return;if(e.code==='Escape'){g.close();this.toggleMap(false);$('settings').hidden=true;return;}if(e.code==='KeyE'&&!g.dialog&&!this.mapOpen)g.interact();if(e.code==='KeyF'&&!g.dialog)g.toggleCart();if(e.code==='KeyV'){g.firstPerson=!g.firstPerson;g.overview=false;this.refresh();}if(e.code==='KeyM')this.toggleMap();if(e.code==='Tab'){g.dialog?g.close():this.menu();}if(e.code==='KeyO'){g.overview=!g.overview;this.refresh();}});
 document.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>{this.keys.clear();this.drag=false;});document.addEventListener('visibilitychange',()=>{this.keys.clear();this.playClock=null;g.save();});
 $('scene').addEventListener('pointerdown',e=>{if(!g.started||g.dialog||this.mapOpen)return;this.drag=true;$('scene').setPointerCapture?.(e.pointerId);this.lastMouse=[e.clientX,e.clientY];});
 $('scene').addEventListener('pointerup',()=>this.drag=false);$('scene').addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('pointermove',e=>{if(this.xr||g.dialog||this.mapOpen)return;let locked=document.pointerLockElement===$('scene');if(this.drag||locked){let dx=locked?e.movementX:e.clientX-this.lastMouse[0],dy=locked?e.movementY:e.clientY-this.lastMouse[1];g.player.yaw-=dx*.003;this.pitch=M.clamp(this.pitch-dy*.003,-1.1,.65);this.lastMouse=[e.clientX,e.clientY];}});
 $('scene').addEventListener('dblclick',()=>{if(g.started&&!g.dialog)$('scene').requestPointerLock?.();});$('scene').addEventListener('wheel',e=>{if(g.overview||!g.started){this.orbitRadius=M.clamp(this.orbitRadius+e.deltaY*.15,180,650);e.preventDefault();}},{passive:false});window.addEventListener('beforeunload',()=>g.save());$('scene').addEventListener('webglcontextlost',e=>{e.preventDefault();fatal(new Error('圖形內容已中斷。請重新整理恢復；任務已儲存在本機。'));});
 }
 start(){if(!this.game.started)this.game.start();$('landing').hidden=true;$('hud').hidden=false;$('recordsBtn').hidden=false;this.refresh();}
 async capabilities(){let supported=false;try{supported=!!navigator.xr&&await navigator.xr.isSessionSupported('immersive-vr');}catch{}this.supported=supported;$('capability').textContent=supported?'沉浸式 VR 可用 · WebGL 2 已啟用':(window.isSecureContext?'WebGL 2 已啟用 · 電腦模式可用':'電腦模式可用 · VR 需 HTTPS');$('vrBtn').textContent=supported?'進入 VR':'VR 支援說明';}
 refresh(){let g=this.game,s=g.state;this.ensureWorld();$('xp').textContent=s.xp+' XP';$('missionTitle').textContent=g.questText;$('missionDesc').textContent=CQ.QUESTS[s.quest]?.desc||'已完成全部任務。可繼續探索，或匯出本機學習紀錄。';$('progressFill').style.width=(s.quest/6*100)+'%';$('viewBtn').textContent=g.firstPerson?'第三人稱 V':'第一人稱 V';$('saveState').textContent=g.storageOK===false?'無法儲存：請匯出紀錄':'本機自動存檔 · 無雲端同步';this.updateXRHud();if(g.dialog)this.showDialog(g.dialog);else this.showDialog(null);if(this.mapOpen)this.buildList();}
 showDialog(d){if(!d){$('dialog').hidden=true;this.panelModel=null;return;}this.keys.clear();document.exitPointerLock?.();$('dialog').hidden=false;$('dialogTitle').textContent=d.title;$('dialogBody').textContent=d.body;let root=$('dialogOptions');root.replaceChildren();d.options.forEach((o,i)=>{let b=document.createElement('button');b.textContent=o.label;b.dataset.option=i;b.onclick=()=>{o.action();this.refresh();};root.append(b);});this.drawPanel();if(this.xr)this.placePanel();}
 menu(){this.game.menu();if(this.xr){let d=this.game.dialog;d.options.splice(d.options.length-1,0,{label:this.smoothVR?'切換為舒適傳送':'開啟左搖桿平移（較易暈眩）',action:()=>{this.smoothVR=!this.smoothVR;this.game.mode=this.smoothVR?'vr-smooth':'vr-teleport';this.game.close();this.game.toast(this.smoothVR?'平移已啟用；左握把仍可傳送。':'已切回舒適傳送。');}},{label:'退出沉浸式 VR',action:()=>this.xr?.end()});this.showDialog(d);}}
 drawPanel(){let c=this.panelCanvas,ctx=c.getContext('2d'),d=this.game.dialog;if(!d)return;ctx.clearRect(0,0,1024,1024);ctx.fillStyle='#102c36';ctx.beginPath();ctx.roundRect(0,0,1024,1024,28);ctx.fill();ctx.strokeStyle='#9ab5bc';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#e9ba79';ctx.font='24px system-ui,sans-serif';ctx.fillText('CAMPUS QUEST / 學生任務平板',48,58);ctx.fillStyle='#f0f4ed';ctx.font='bold 42px system-ui,"Microsoft JhengHei",sans-serif';let title=wrap(ctx,d.title,920);title.slice(0,2).forEach((l,i)=>ctx.fillText(l,48,119+i*49));let titleEnd=title.length>1?185:143;let count=d.options.length,bottom=970,start=bottom-count*83;ctx.font='28px system-ui,"Microsoft JhengHei",sans-serif';ctx.fillStyle='#c9d8db';let lines=wrap(ctx,d.body,922),limit=Math.floor((start-titleEnd-18)/37);lines.slice(0,limit).forEach((l,i)=>ctx.fillText(l,48,titleEnd+i*37+30));if(lines.length>limit){ctx.font='20px system-ui,sans-serif';ctx.fillText('完整說明另見電腦版與操作手冊。',48,start-10);}this.panelRects=[];d.options.forEach((o,i)=>{let y=start+i*83;ctx.fillStyle=i===0?'#3e5052':'#203f48';ctx.beginPath();ctx.roundRect(36,y,952,70,12);ctx.fill();ctx.fillStyle=i===0?'#f3cb8c':'#e0e9e7';ctx.font='30px system-ui,"Microsoft JhengHei",sans-serif';ctx.fillText(o.label,58,y+45,900);this.panelRects.push({x:36,y,w:952,h:70,index:i});});this.r.updateTexture(this.panelTexture,c);}
 updateXRHud(){if(!this.hudTexture)return;let text=this.game.questText,sub=this.game.toastText&&performance.now()<this.game.toastUntil?this.game.toastText:'左握把：傳送｜右扳機：互動｜X：任務平板';if(this.game.state.fiveS.held!==null)sub='手持：'+['扳手 → 常用工具區','空紙箱 → 可回收物區','損壞電纜 → 待維修隔離區'][this.game.state.fiveS.held];let c=CQ.makeText(text,sub,1024,150);this.r.updateTexture(this.hudTexture,c);}
 placePanel(){if(!this.xr)return;let p=this.eye,yaw=this.headYaw;this.panelYaw=yaw;this.panelModel=M.trs(p[0]-Math.sin(yaw)*2.15,p[1]-.05,p[2]-Math.cos(yaw)*2.15,yaw,1.38,1.38,1);}
 toggleMap(force){if(this.xr)return;this.mapOpen=force===undefined?!this.mapOpen:force;$('mapPanel').hidden=!this.mapOpen;this.keys.clear();if(this.mapOpen){document.exitPointerLock?.();this.buildList();this.drawMap($('fullmap'),true);}}
 buildList(){let root=$('buildingList');root.replaceChildren();let recover=document.createElement('button');recover.textContent='恢復目前任務導航';recover.onclick=()=>{this.game.navOverride=null;this.toggleMap(false);this.lastRoute=-100;};root.append(recover);for(const b of CQ.DATA.buildings){let d=document.createElement('div');d.className='buildingRow';let t=document.createElement('strong');t.textContent=(this.game.state.visited.includes(b.id)?'✓ ':'')+b.name;let sub=document.createElement('small');sub.textContent=b.interior?'外部探索＋示意室內':'外部探索 · 立面簡化';let a=document.createElement('button');a.textContent='設定導航';a.onclick=()=>{if(this.game.player.scene!=='campus')this.game.exit();this.game.navOverride=b.id;this.toggleMap(false);this.lastRoute=-100;this.game.toast('導航目標：'+b.name);};let go=document.createElement('button');go.textContent='快速導覽';go.onclick=()=>{if(this.game.player.scene!=='campus')this.game.exit();this.game.cart.driving=false;this.game.teleport(...b.door,{assist:true,kind:'map-fast-travel'});this.game.navOverride=b.id;this.toggleMap(false);this.lastRoute=-100;this.game.toast('已快速到達；如在配送中，本次記為導覽輔助。');};d.append(t,sub,a,go);root.append(d);}}
 drawMap(canvas,full=false){let ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,g=this.game,p=g.player;ctx.fillStyle='#132d37';ctx.fillRect(0,0,w,h);let bounds=g.world.bounds,scale=full?Math.min((w-75)/(bounds.maxX-bounds.minX),(h-95)/(bounds.maxZ-bounds.minZ)):(p.scene==='campus'?2.25:15),cx=full?(bounds.minX+bounds.maxX)/2:p.x,cz=full?(bounds.minZ+bounds.maxZ)/2:p.z,xy=(x,z)=>[w/2+(x-cx)*scale,h/2+(z-cz)*scale];ctx.strokeStyle='#64808822';ctx.lineWidth=1;for(let x=Math.floor(bounds.minX/25)*25;x<bounds.maxX;x+=25){let a=xy(x,bounds.minZ),b=xy(x,bounds.maxZ);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();}for(let z=Math.floor(bounds.minZ/25)*25;z<bounds.maxZ;z+=25){ctx.beginPath();ctx.moveTo(...xy(bounds.minX,z));ctx.lineTo(...xy(bounds.maxX,z));ctx.stroke();}
 if(p.scene==='campus'){let rs=[[[-83,88],[-83,-177],[88,-177],[88,99],[15,109],[-45,108],[-83,88]],[[8,255],[8,211],[-8,164],[-45,108]],[[-8,164],[34,166],[88,99]],[[-83,88],[-212,31],[-216,-205],[-194,-242]]];ctx.strokeStyle='#7c919044';ctx.lineWidth=11*scale;for(let r of rs){ctx.beginPath();r.forEach((a,i)=>i?ctx.lineTo(...xy(...a)):ctx.moveTo(...xy(...a)));ctx.stroke();}let f=xy(-169,-113);ctx.fillStyle='#5e686133';ctx.beginPath();ctx.ellipse(...f,42*scale,93*scale,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#b2936c77';ctx.lineWidth=7*scale;ctx.stroke();}
 for(const b of g.world.boxes){let a=xy(b.x-b.w/2,b.z-b.d/2);ctx.fillStyle=p.scene==='campus'?'#50636a':'#627273';ctx.fillRect(...a,b.w*scale,b.d*scale);ctx.strokeStyle='#91a5a766';ctx.lineWidth=1;ctx.strokeRect(...a,b.w*scale,b.d*scale);}
 if(this.route&&p.scene==='campus'){ctx.strokeStyle='#e8b674';ctx.lineWidth=full?3:4;ctx.setLineDash([7,5]);ctx.beginPath();this.route.points.forEach((a,i)=>i?ctx.lineTo(...xy(a.x,a.z)):ctx.moveTo(...xy(a.x,a.z)));ctx.stroke();ctx.setLineDash([]);}
 if(full&&p.scene==='campus'){ctx.textAlign='center';for(const b of CQ.DATA.buildings){let a=xy(b.x,b.z);ctx.fillStyle='#f0f0e4';ctx.font='500 16px system-ui,"Microsoft JhengHei",sans-serif';ctx.fillText(b.name,...a,Math.max(90,b.w*scale+12));}for(let id of ['TRACK','PLAZA','BUS','DORM2']){let q=CQ.DATA.places.find(p=>p.id===id);ctx.fillStyle='#b7c6c5';ctx.font='13px system-ui,sans-serif';ctx.fillText(q.name,...xy(q.x,q.z));}}
 let target=g.objective();if(target){ctx.fillStyle='#edbe7c';ctx.beginPath();ctx.arc(...xy(target.x,target.z),full?7:9,0,Math.PI*2);ctx.fill();}let pp=xy(p.x,p.z);ctx.save();ctx.translate(...pp);ctx.rotate(-p.yaw);ctx.fillStyle='#f3f6ee';ctx.beginPath();ctx.moveTo(0,-11);ctx.lineTo(7,8);ctx.lineTo(0,4);ctx.lineTo(-7,8);ctx.closePath();ctx.fill();ctx.restore();if(full){ctx.textAlign='left';ctx.fillStyle='#b8cace';ctx.font='14px system-ui,sans-serif';ctx.fillText('上方：宿舍區方向（非正北）｜金色：目前目標｜白色：玩家',25,30);}}
 updateDesktop(dt){let g=this.game,p=g.player;if(!g.started||g.dialog||this.mapOpen||!$('settings').hidden||g.overview){g.moving=false;return;}let k=this.keys,fw=(k.has('KeyW')||k.has('ArrowUp')?1:0)-(k.has('KeyS')||k.has('ArrowDown')?1:0),side=(k.has('KeyD')||k.has('ArrowRight')?1:0)-(k.has('KeyA')||k.has('ArrowLeft')?1:0);if(g.cart.driving){let c=g.cart;c.speed=M.clamp(c.speed+fw*4*dt,-3,9);if(!fw)c.speed*=Math.exp(-1.8*dt);if(k.has('Space'))c.speed*=Math.exp(-12*dt);p.yaw-=side*dt*1.1*M.clamp(Math.abs(c.speed),0,1);let d=g.move(-Math.sin(p.yaw)*c.speed*dt,-Math.cos(p.yaw)*c.speed*dt);if(d<Math.abs(c.speed*dt)*.3)c.speed=0;g.moving=d>.001;}else{let len=Math.hypot(fw,side)||1,speed=k.has('ShiftLeft')||k.has('ShiftRight')?6.2:3.2,dx=(-Math.sin(p.yaw)*fw+Math.cos(p.yaw)*side)*speed*dt/len,dz=(-Math.cos(p.yaw)*fw-Math.sin(p.yaw)*side)*speed*dt/len;g.moving=g.move(dx,dz)>.001;}}
 desktopCamera(t){let g=this.game,p=g.player;if(!g.started||g.overview){let angle=g.started?p.yaw:Math.sin(t*.000055)*.13;let r=this.orbitRadius;if(p.scene==='campus'){let eye=[Math.sin(.74+angle)*r,190+Math.abs(r-365)*.2,Math.cos(.74+angle)*r-20];return{eye,target:[-18,5,-38]};}return{eye:[15,21,24],target:[0,0,0]};}let floor=g.floor(),eyeY=g.cart.driving?1.90:1.66,forward=[-Math.sin(p.yaw)*Math.cos(this.pitch),Math.sin(this.pitch),-Math.cos(p.yaw)*Math.cos(this.pitch)],focus=[p.x,floor+eyeY,p.z];if(g.firstPerson)return{eye:focus,target:M.add(focus,forward)};let distance=g.cart.driving?8:6.4,eye=M.sub(focus,M.scale(forward,distance));for(let k=1;k<=20;k++){let tt=k/20,q={x:focus[0]+(eye[0]-focus[0])*tt,z:focus[2]+(eye[2]-focus[2])*tt};if(CQ.collision(q.x,q.z,g.world.boxes,.18)){eye=M.add(focus,M.scale(M.sub(eye,focus),Math.max(.06,(k-1)/20)));break;}}eye[1]=Math.max(eye[1],g.floor(eye[0],eye[2])+.4);return{eye,target:focus};}
 updateRoute(t){let g=this.game,target=g.objective();if(g.player.scene!=='campus'||!target){this.route=null;return;}let key=target.id;if(t-this.lastRoute<4000&&key===this.routesKey)return;this.lastRoute=t;this.routesKey=key;this.route=CQ.pathfind({x:g.player.x,z:g.player.z},target,g.world.boxes);let geo=new CQ.G();if(this.route)for(let i=0;i<this.route.points.length-1;i++)geo.road(this.route.points[i],this.route.points[i+1],.20,[.95,.66,.27],.18);this.r.update(this.routeMesh,geo);}
 updateDynamic(t){let g=this.game,p=g.player,geo=new CQ.G(),target=g.objective();
 for(let a of g.interactables()){if(M.dist(a,p)>65&&!g.overview)continue;let y=g.floor(a.x,a.z),active=target?.id===a.id,col=active?[.99,.68,.27]:[.38,.66,.64];geo.ring(a.x,y+.05,a.z,active?1.05:.52,active?1.05:.52,.13,col,20);if(active){geo.cylinder(a.x,y+2.9+Math.sin(t*.003)*.13,a.z,.27,.55,col,4,0);geo.cylinder(a.x,y+2.35+Math.sin(t*.003)*.13,a.z,0,.55,col,4,.27);}}
 if(p.scene==='campus'){let y=CQ.ground(2,188);for(let i=0;i<3;i++)geo.box(1+i*.9,y+.4,188,.7,.8,.7,[.61,.46,.29]);}else if(p.scene==='lab'){
 for(let i=0;i<3;i++)if(!g.state.fiveS.sorted.includes(i)&&g.state.fiveS.held!==i){let x=-4+i*4,z=3.7;if(i===0){geo.box(x,.17,z,.14,.14,.8,[.68,.71,.70]);geo.cylinder(x,.18,z-.45,.22,.12,[.68,.71,.70],6);}if(i===1){geo.box(x,.33,z,.65,.65,.65,[.64,.48,.29]);geo.box(x,.66,z,.03,.012,.65,[.82,.72,.49]);}if(i===2){geo.ring(x,.08,z,.40,.4,.1,[.18,.23,.25],16);geo.box(x+.35,.14,z,.15,.2,.25,[.69,.33,.24]);}}
 for(let i=0;i<8;i++){let x=((t*.0009+i*2.1)%17)-8;geo.box(x,1.01,-3.7,.32,.24,.42,[.65,.56,.36]);}
 }
 for(let l of this.xrLines){if(l.points)for(let i=0;i<l.points.length-1;i++)beam(geo,l.points[i],l.points[i+1],l.color,.01);else beam(geo,l.a,l.b,l.color,.004);if(l.end)geo.sphere(...l.end,.045,.045,.045,l.color,6,4);}
 this.r.update(this.dynamic,geo);if(t-this.lastDynamic>75){this.lastDynamic=t;this.r.update(this.avatarMesh,CQ.makeAvatar([.21,.40,.47],t/1000,g.moving));}}
 drawWorld(vp,eye,t,clear=true){let r=this.r,g=this.game,p=g.player,w=g.world;this.eye=eye;r.fog=p.scene==='campus'?[.64,.76,.81]:[.47,.57,.61];r.begin(vp,eye,clear);r.draw(w.mesh);if(this.route&&p.scene==='campus'&&g.started)r.draw(this.routeMesh);r.draw(this.dynamic);
 if(p.scene==='campus'){
 r.draw(this.cartMesh,M.trs(g.cart.x,CQ.ground(g.cart.x,g.cart.z),g.cart.z,g.cart.yaw));
 r.draw(this.npcMesh2,M.trs(13,CQ.ground(13,203),203,.6));
 let pts=[[-18,-86],[81,-86],[81,-4],[-18,-4]],lengths=[99,82,99,82],sum=362;
 for(let i=0;i<9;i++){let u=(t*.001*.95+i*39)%sum,k=0;while(u>lengths[k])u-=lengths[k++];let a=pts[k],b=pts[(k+1)%4],s=u/lengths[k],x=a[0]+(b[0]-a[0])*s,z=a[1]+(b[1]-a[1])*s;if(Math.hypot(x-eye[0],z-eye[2])>150&&!g.overview&&g.started)continue;let yaw=Math.atan2(-(b[0]-a[0]),-(b[1]-a[1]));r.draw(i%2?this.npcMesh:this.npcMesh2,M.trs(x,CQ.ground(x,z)+Math.sin(t*.009+i)*.015,z,yaw));}
 }
 if(g.started&&!g.firstPerson&&!this.xr&&!g.overview)r.draw(this.avatarMesh,M.trs(p.x,g.floor()+(g.cart.driving?.58:0),p.z,p.yaw,1,g.cart.driving?.70:1,1));
 if(g.state.fiveS.held!==null&&g.player.scene==='lab'){let model;let right=[...this.rays.entries()].find(([src])=>src.handedness==='right')?.[1];if(this.xr&&right)model=M.mul(right.tm,M.trs(.03,-.07,-.15));else model=M.mul(M.trs(p.x,g.floor()+1.05,p.z,p.yaw),M.trs(.44,0,-.35));r.draw(this.heldMeshes[g.state.fiveS.held],model);}
 for(let l of w.labels){let dist=Math.hypot(l.x-eye[0],l.z-eye[2]);if(p.scene!=='campus'&&g.started&&!g.overview&&!g.firstPerson&&!this.xr&&dist<Math.hypot(p.x-eye[0],p.z-eye[2])*.83)continue;if(dist>(!g.started||g.overview?650:(this.xr?85:125)))continue;let yaw=Math.atan2(eye[0]-l.x,eye[2]-l.z);let ls=(!g.started||g.overview)?1.5:1;if(p.scene!=='campus'&&!g.overview)ls=Math.min(ls,Math.max(.24,dist*.22/l.w));r.label(l.tex,M.trs(l.x,l.y,l.z,yaw,l.w*ls,l.h*ls,1));}
 if(this.xr){let yaw=this.headYaw,forward=[-Math.sin(yaw),0,-Math.cos(yaw)],loc=M.add(this.headWorld,M.scale(forward,1.9));loc[1]-=.56;r.label(this.hudTexture,M.trs(...loc,yaw,1.08,.158,1),true);if(g.dialog&&this.panelModel)r.label(this.panelTexture,this.panelModel,true);}
 }
 tick(t,dt){let elapsed=this.playClock===null?0:Math.max(0,(t-this.playClock)/1000);this.playClock=t;if(this.game.started&&document.visibilityState!=='hidden'){this.game.state.playSeconds+=elapsed;if(this.game.state.playSeconds-this.game.lastSave>5)this.game.save();}this.ensureWorld();this.updateRoute(t);this.updateDynamic(t);if(t-this.lastHUD>220){this.lastHUD=t;let g=this.game,target=g.objective(),nearest=g.nearest(),distance=target?M.dist(g.player,target):0;let zone=g.player.scene==='campus'?'主校區':({lab:'工管教學實驗室 · 示意',classroom:'示意教室',library:'示意閱讀空間'}[g.player.scene]);$('zone').textContent=zone;$('nextTarget').textContent=target?`下一站：${target.name} · ${Math.round(distance)} 虛擬公尺`:'';$('prompt').hidden=!nearest||!!g.dialog||this.mapOpen;if(nearest)$('promptName').textContent=nearest.name;$('coord').textContent=`${Math.round(g.player.x)}, ${Math.round(g.player.z)}`;$('maploc').textContent=zone;if(performance.now()>g.toastUntil)$('toast').hidden=true;this.drawMap($('minimap'));if(this.mapOpen)this.drawMap($('fullmap'),true);if(this.xr)this.updateXRHud();}
 this.stats.frames++;if(t-this.stats.start>1000){this.stats.fps=Math.round(this.stats.frames*1000/(t-this.stats.start));this.stats.frames=0;this.stats.start=t;$('perf').textContent=this.stats.fps+' FPS · '+Math.round(this.r.triangles/1000)+'k triangles / view';}}
 frame(t){requestAnimationFrame(n=>this.frame(n));if(this.xr)return;let dt=Math.min((t-this.lastTick)/1000,.05);this.lastTick=t;this.updateDesktop(dt);this.tick(t,dt);let {eye,target}=this.desktopCamera(t);this.r.gl.bindFramebuffer(this.r.gl.FRAMEBUFFER,null);this.r.resize();let vp=M.mul(M.persp(Math.PI/3,innerWidth/innerHeight,(!this.game.started||this.game.overview)?2:.18,1250),M.look(eye,target));this.drawWorld(vp,eye,t);}
 async enterVR(){if(this.xrBusy)return;this.xrBusy=true;let session;try{
 if(!window.isSecureContext)throw new Error('沉浸式 VR 需要 HTTPS 安全網址。一般 http://電腦IP 只能顯示平面網頁；請依操作手冊使用 HTTPS 或 USB localhost 測試。');
 if(!navigator.xr||!await navigator.xr.isSessionSupported('immersive-vr'))throw new Error('此瀏覽器沒有可用的沉浸式 VR 裝置。請在 Quest 3 的 Meta Quest Browser 開啟同一個 HTTPS 網址。電腦仍可按「進入校園」遊玩。');
 session=await navigator.xr.requestSession('immersive-vr',{requiredFeatures:['local-floor'],optionalFeatures:['bounded-floor']});await this.r.gl.makeXRCompatible();let layer=new XRWebGLLayer(session,this.r.gl,{alpha:false,antialias:true,framebufferScaleFactor:.85});session.updateRenderState({baseLayer:layer,depthNear:.08,depthFar:900});try{if('fixedFoveation' in layer)layer.fixedFoveation=.6;}catch{}
 this.xrSpace=await session.requestReferenceSpace('local-floor');this.xr=session;this.setQuality('balanced');this.game.mode='vr-teleport';this.game.cart.driving=false;this.game.cart.speed=0;this.xrDesiredYaw=this.game.player.yaw;this.xrNeedsAlign=true;this.game.firstPerson=true;this.game.overview=false;this.start();document.body.classList.add('xr');this.game.close();this.game.log('xr_session_start',{referenceSpace:'local-floor',hardwareVerification:'not_recorded'});this.keys.clear();session.addEventListener('end',()=>this.exitVR());session.addEventListener('select',e=>this.xrSelect(e.inputSource));session.addEventListener('visibilitychange',()=>this.keys.clear());session.requestAnimationFrame((t,f)=>this.xrFrame(t,f));
 }catch(e){if(session&&!this.xr)try{await session.end();}catch{}this.start();this.game.open('VR 啟動說明',e.message||String(e));$('landing').hidden=true;$('dialog').hidden=false;}finally{this.xrBusy=false;}}
 exitVR(){this.xr=null;this.xrSpace=null;this.xrLines=[];this.rays.clear();this.buttons.clear();this.teleports.clear();this.game.mode='desktop';this.game.firstPerson=true;this.game.close();document.body.classList.remove('xr');this.r.gl.bindFramebuffer(this.r.gl.FRAMEBUFFER,null);this.lastTick=performance.now();this.game.log('xr_session_end');this.refresh();}
 xrSelect(source){let ray=this.rays.get(source);if(!ray)return;if(this.game.dialog&&this.panelModel){let inv=M.inverseRigid(M.trs(this.panelModel[12],this.panelModel[13],this.panelModel[14],this.panelYaw??this.headYaw)),o=M.point(inv,ray.o),d=M.dir(inv,ray.d),t=-o[2]/d[2];if(t>0&&Number.isFinite(t)){let x=(o[0]+d[0]*t)/1.38*1024+512,y=512-(o[1]+d[1]*t)/1.38*1024;let rect=this.panelRects.find(r=>x>=r.x&&x<=r.x+r.w&&y>=r.y&&y<=r.y+r.h);if(rect){let option=this.game.dialog.options[rect.index];option?.action();this.refresh();try{source.gamepad?.hapticActuators?.[0]?.pulse(.3,40);}catch{}}}return;}
 let best=null,score=Infinity;for(const target of this.game.interactables()){if(M.dist(this.game.player,target)>5.8)continue;let center=[target.x,this.game.floor(target.x,target.z)+1.1,target.z],v=M.sub(center,ray.o),proj=M.dot(v,ray.d),side=Math.hypot(...M.sub(v,M.scale(ray.d,proj)));if(proj>0&&side<1.3&&proj<score){score=proj;best=target;}}if(best){this.game.interact(best.id);this.placePanel();this.panelYaw=this.headYaw;}else{let nearby=this.game.nearest();if(nearby)this.game.interact(nearby.id);else this.game.toast('請靠近金色標記，用右扳機互動。');if(this.game.dialog){this.placePanel();this.panelYaw=this.headYaw;}}}
 rig(){return M.trs(this.game.player.x,this.game.floor(),this.game.player.z,this.game.player.yaw);}
 arc(ray){let points=[ray.o],prev=ray.o,hit=null;for(let i=1;i<=90;i++){let t=i*.024,p=M.add(ray.o,M.add(M.scale(ray.d,t*8),[0,-4.9*t*t,0]));let floor=this.game.floor(p[0],p[2]);points.push(p);if(p[1]<=floor+.03){let ratio=(prev[1]-this.game.floor(prev[0],prev[2]))/((prev[1]-this.game.floor(prev[0],prev[2]))-(p[1]-floor));let x=prev[0]+(p[0]-prev[0])*ratio,z=prev[2]+(p[2]-prev[2])*ratio;hit={x,z};points[points.length-1]=[x,this.game.floor(x,z)+.04,z];break;}if(!this.game.canStand(p[0],p[2],.25)){break;}prev=p;}let valid=hit&&this.game.canStand(hit.x,hit.z)&&M.dist(this.game.player,hit)<14&&CQ.lineClear(this.game.player,hit,this.game.world.boxes);return{points,hit:valid?hit:null};}
 xrFrame(t,frame){let session=this.xr;if(!session)return;session.requestAnimationFrame((tt,f)=>this.xrFrame(tt,f));let pose=frame.getViewerPose(this.xrSpace);if(!pose)return;let dt=Math.min((t-this.lastTick)/1000,.04);this.lastTick=t;
 this.ensureWorld();let mat=pose.transform.matrix,local=[mat[12],mat[13],mat[14]],localYaw=Math.atan2(mat[8],mat[10]);this.headLocal=local;
 if(this.xrNeedsAlign){this.game.player.yaw=this.xrDesiredYaw-localYaw;let offset=M.dir(M.trs(0,0,0,this.game.player.yaw),local);this.game.player.x-=offset[0];this.game.player.z-=offset[2];this.xrNeedsAlign=false;this.panelModel=null;}
 let rig=this.rig();this.headWorld=M.point(rig,local);this.headYaw=this.game.player.yaw+localYaw;this.eye=this.headWorld;this.xrLines=[];this.game.moving=false;
 for(const source of session.inputSources){let p=frame.getPose(source.targetRaySpace,this.xrSpace);if(!p)continue;let tm=M.mul(rig,p.transform.matrix),o=[tm[12],tm[13],tm[14]],d=M.norm([-tm[8],-tm[9],-tm[10]]),ray={o,d,tm};this.rays.set(source,ray);let gp=source.gamepad,prev=this.buttons.get(source)||[],buttons=gp?.buttons.map(b=>b.pressed)||[],axes=gp?.axes||[],ax=axes.length>=4?axes[2]:(axes[0]||0),az=axes.length>=4?axes[3]:(axes[1]||0);
 if(source.handedness==='left'){
  if(buttons[4]&&!prev[4]){this.game.dialog?this.game.close():this.menu();this.panelYaw=this.headYaw;}
  if(buttons[1]&&!this.game.dialog){let a=this.arc(ray);this.teleports.set(source,a.hit);this.xrLines.push({points:a.points,color:a.hit?[.96,.70,.32]:[.79,.30,.24],end:a.points.at(-1)});}
  else if(prev[1]){let hit=this.teleports.get(source);if(hit&&!this.game.dialog){this.game.teleport(hit.x,hit.z,{kind:'vr-controller-teleport',y:hit.y});try{gp?.hapticActuators?.[0]?.pulse(.35,55);}catch{}}this.teleports.delete(source);}
  if(this.smoothVR&&!this.game.dialog&&Math.hypot(ax,az)>.2){let yaw=this.headYaw,len=Math.max(1,Math.hypot(ax,az));this.game.moving=this.game.move((Math.cos(yaw)*ax+Math.sin(yaw)*az)*1.65*dt/len,(-Math.sin(yaw)*ax+Math.cos(yaw)*az)*1.65*dt/len)>.0001;}
 }else{
  if(buttons[1]&&!prev[1]){this.game.dialog?this.game.close():this.menu();this.panelYaw=this.headYaw;}
  if(Math.abs(ax)>.7&&!(prev.snap)&&!this.game.dialog){let before=M.dir(M.trs(0,0,0,this.game.player.yaw),local);this.game.player.yaw-=Math.sign(ax)*Math.PI/6;let after=M.dir(M.trs(0,0,0,this.game.player.yaw),local);this.game.player.x+=before[0]-after[0];this.game.player.z+=before[2]-after[2];}
  buttons.snap=Math.abs(ax)>.4;
 }
 this.buttons.set(source,buttons);if(!buttons[1]||source.handedness!=='left')this.xrLines.push({a:o,b:M.add(o,M.scale(d,this.game.dialog?2.5:3.5)),color:[.46,.79,.80]});
 }
 if(this.game.dialog&&!this.panelModel){this.placePanel();this.panelYaw=this.headYaw;}
 rig=this.rig();this.headWorld=M.point(rig,local);this.headYaw=this.game.player.yaw+localYaw;this.game.trackedFeet={x:this.headWorld[0],z:this.headWorld[2]};this.tick(t,dt);let gl=this.r.gl,layer=session.renderState.baseLayer;gl.bindFramebuffer(gl.FRAMEBUFFER,layer.framebuffer);gl.clearColor(.64,.76,.81,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);
 let blocked=!this.game.canStand(this.headWorld[0],this.headWorld[2],.20),invRig=M.inverseRigid(rig);
 for(const view of pose.views){let viewport=layer.getViewport(view);gl.viewport(viewport.x,viewport.y,viewport.width,viewport.height);let vp=M.mul(view.projectionMatrix,M.mul(view.transform.inverse.matrix,invRig)),camera=M.point(rig,[view.transform.matrix[12],view.transform.matrix[13],view.transform.matrix[14]]);if(blocked){this.r.begin(vp,camera,false);if(!this.game.dialog){this.game.toast('靠近建築邊界：請退一步，或按 X 返回安全地點。');}let pos=M.add(this.headWorld,[-Math.sin(this.headYaw)*1.6,-.3,-Math.cos(this.headYaw)*1.6]);this.r.label(this.hudTexture,M.trs(...pos,this.headYaw,1.1,.18,1),true);if(this.panelModel&&this.game.dialog)this.r.label(this.panelTexture,this.panelModel,true);}else this.drawWorld(vp,camera,t,false);}
 }
}
try{CQ.installAppV2(App);const app=new App();window.CampusQuest={app,game:app.game,renderer:app.r,version:CQ.DATA.version};}catch(e){fatal(e);}
})();
