'use strict';
/* Keep the six original learning tasks, but bind them to actual 3D floors.
 * Vertical distance is part of every interaction and teleport validation.
 */
(()=>{
const Base=CQ.Game,D=CQ.DATA,M=CQ.M;
CQ.QUESTS[0].desc='進入理工大樓，沿樓梯或使用樓層轉場，到 5F 工管系服務點報到。';
CQ.QUESTS[3].desc='到理工大樓 6F 教學實驗室，拾取三件物品，送至適當的 5S 分類區。';
CQ.QUESTS[4].desc='在理工大樓 6F 比較三站加工時間，改善限制整條產線的瓶頸。';
class Game extends Base{
 constructor(){super();this.player.y=this.world.physics.support(this.player.x,this.player.z,CQ.ground(this.player.x,this.player.z)+.3).y;this.firstPerson=true;this.fadeUntil=0;this.liftPending=null;}
 reset(){super.reset();this.player.y=this.world.physics.support(this.player.x,this.player.z,CQ.ground(this.player.x,this.player.z)+.3).y;this.firstPerson=true;this.liftPending=null;}
 start(){this.started=true;this.log('session_start',{schema:2,build:D.version,geometry:'authored-photo-informed'});this.toast('歡迎來到朝陽。理工大樓 5F 報到；門廳可選擇樓層，也能逐階走上樓。');this.changed();}
 floor(x=this.player.x,z=this.player.z){if(x===this.player.x&&z===this.player.z&&Number.isFinite(this.player.y))return this.player.y;let y=this.world.physics.support(x,z,(this.player.y??CQ.ground(x,z))+.24).y;return Number.isFinite(y)?y:CQ.ground(x,z)+.045;}
 location(){return this.world.physics.location(this.player);}
 canStand(x,z,r=.3,y=this.player.y){return this.world.physics.safe(x,Number.isFinite(y)?y:CQ.ground(x,z)+.045,z,r);}
 move(dx,dz){if(this.liftPending)return 0;let d=this.world.physics.move(this.player,dx,dz,this.cart.driving?.91:.30);if(this.state.route.active)this.state.route.distance+=d;if(this.cart.driving){Object.assign(this.cart,{x:this.player.x,z:this.player.z,yaw:this.player.yaw});}return d;}
 step(dt){if(this.liftPending){if(performance.now()>=this.liftPending.at){let p=this.liftPending;this.liftPending=null;this.teleport(p.x,p.z,{y:p.y,assist:true,kind:'elevator-comfort-transfer'});if(!this.mode.startsWith('vr'))this.player.yaw=Math.PI;this.toast(p.name+' · '+p.floor+'F。已完成舒適樓層轉場。');}return;}if(this.started){let p=this.player,sp=this.world.physics;if(this.mode.startsWith('vr')&&this.trackedFeet){let foot={x:this.trackedFeet.x,z:this.trackedFeet.z,y:p.y,vy:p.vy},s=sp.support(foot.x,foot.z,p.y+.24);if(s.y>=p.y-.20&&s.y<=p.y+.24&&sp.safe(foot.x,s.y,foot.z))foot.y=s.y;sp.gravity(foot,dt);p.y=foot.y;p.vy=foot.vy;}else sp.gravity(p,dt);}}
 teleport(x,z,{y=null,assist=false,kind='vr-teleport'}={}){let p=this.player,sp=this.world.physics;if(y===null)y=sp.support(x,z,CQ.ground(x,z)+.35).y;if(!Number.isFinite(y)||!sp.safe(x,y,z,this.cart.driving?.91:.30))return false;
 let ground=sp.support(x,z,y+.12);if(!Number.isFinite(ground.y)||Math.abs(ground.y-y)>.30)return false;
 if(!assist){if(Math.hypot(x-p.x,z-p.z)>16||Math.abs(y-p.y)>2.16)return false;let h=sp.segment([p.x,p.y+1.35,p.z],[x,y+1.35,z]);if(h&&h.type==='wall')return false;}
 if(this.state.route.active){this.state.route.distance+=Math.hypot(x-p.x,y-p.y,z-p.z);if(assist)this.state.route.assisted=true;}if(assist)this.state.assists++;Object.assign(p,{x,y:ground.y,z,vy:0});this.log('teleport',{x,y:ground.y,z,assist,kind});this.onTeleport?.();this.changed();return true;}
 safeEntrance(b){let q=this.world.entrances[b.id]||{x:b.door[0],z:b.door[1],y:CQ.ground(...b.door)+.045};for(let dx of [0,.7,-.7,1.3,-1.3])for(let dz of [0,.7,-.7,1.3,-1.3]){let x=q.x+dx,z=q.z+dz,y=this.world.physics.support(x,z,b.base+.2).y;if(this.world.physics.safe(x,y,z))return{x,z,y};}return{x:b.door[0],z:b.door[1],y:CQ.ground(...b.door)+.045};}
 enter(key,b){let q=this.safeEntrance(b);this.cart.driving=false;this.cart.speed=0;this.teleport(q.x,q.z,{...q,assist:true,kind:'entrance-guide'});this.close();this.toast('已到 '+b.name+' 門廳。沿走廊前進，樓梯與樓層面板在建築南側。');}
 exit(){let b=D.buildings.find(b=>b.id===this.location().building)||D.buildings.find(b=>b.id==='E');this.teleport(...b.door,{assist:true,kind:'exit-guide'});this.close();}
 lift(bid,f){let b=D.buildings.find(b=>b.id===bid);if(!b||f<1||f>b.floors)return false;let target={x:b.lift.x,z:b.lift.z-.85,y:b.base+(f-1)*b.floorHeight};if(!this.world.physics.safe(target.x,target.y,target.z))return false;this.close();this.cart.driving=false;this.liftPending={...target,floor:f,name:b.name,at:performance.now()+300};this.fadeUntil=performance.now()+650;this.log('floor_transfer_requested',{building:bid,toFloor:f,method:'fade-comfort-transfer-not-mechanical-elevator'});return true;}
 interactables(){let a=[{id:'WELCOME',name:'迎新學長',x:13,z:203},{id:'SUPPLY',name:'校園物流點',x:2,z:188},{id:'CART',name:'電動搬運車',x:this.cart.x,z:this.cart.z},...D.buildings.map(b=>({id:b.id,name:b.name,x:b.door[0],z:b.door[1]})),...D.places.filter(p=>!['GATE','BUS','P1','P2','P3','PLAZA'].includes(p.id))].map(t=>({...t,y:CQ.ground(t.x,t.z)+.045}));
 return a.concat(this.world.lifts,this.world.learning.filter(t=>!t.id.startsWith('ITEM')||(!this.state.fiveS.sorted.includes(+t.id.slice(4))&&this.state.fiveS.held!==+t.id.slice(4))));}
 nearest(){let p=this.player,sp=this.world.physics,n=null,d=Infinity;for(let t of this.interactables()){if(Math.abs(t.y-p.y)>.9)continue;let dd=Math.hypot(t.x-p.x,t.y-p.y,t.z-p.z);if(dd<d&&dd<4.2){let hit=sp.segment([p.x,p.y+1.35,p.z],[t.x,t.y+1.1,t.z]);if(!hit||hit.t>.92){n=t;d=dd;}}}return n?{...n,distance:d}:null;}
 objective(){let s=this.state;if(this.navOverride)return this.targetFor(this.navOverride);if(s.quest===0)return this.targetFor('OFFICE5');if(s.quest===1)return this.targetFor(['T','D','L'].find(x=>!s.signed.includes(x))||'E');if(s.quest===2){if(!s.route.pickup)return this.targetFor('SUPPLY');return this.targetFor((s.route.best?.order||D.delivery).find(id=>!s.route.delivered.includes(id))||'E');}if(s.quest===3)return this.targetFor(s.fiveS.held!==null?'BIN'+s.fiveS.held:'ITEM'+[0,1,2].find(i=>!s.fiveS.sorted.includes(i)));if(s.quest===4)return this.targetFor('ST'+([0,1,2].find(i=>!s.seenStations.includes(i))??1));if(s.quest===5)return this.targetFor('QC');return null;}
 inspectBuilding(b){let s=this.state;if(!s.visited.includes(b.id)){s.visited.push(b.id);this.log('building_discovered',{id:b.id});}if(!s.signed.includes(b.id))s.signed.push(b.id);if(s.quest===1&&['T','D','L'].every(x=>s.signed.includes(x)))this.complete();let opts=[];
 if(s.quest===2&&s.route.pickup&&D.delivery.includes(b.id)&&!s.route.delivered.includes(b.id))opts.push({label:'交付教學材料',action:()=>{s.route.delivered.push(b.id);this.log('delivery',{building:b.id,distance:s.route.distance});this.toast('已交付 '+b.name);this.close();this.changed();}});
 if(b.id==='E'&&s.quest===2&&s.route.delivered.length===3)opts.push({label:'結算配送任務',action:()=>{s.route.active=false;this.log('delivery_completed',{distance:s.route.distance,best:s.route.best?.length,assisted:s.route.assisted});this.complete();this.open('配送完成',`行走距離 ${s.route.distance.toFixed(1)} 模型公尺。\n格網參考路程 ${s.route.best?.length?.toFixed(1)||'未計算'} 模型公尺。\n${s.route.assisted?'使用過導覽輔助，不比較路徑效率。':'計算基於重建座標，不是實測校園距離。'}\n下一站：理工大樓 6F 教學實驗室。`);}});
 if(b.enterable)opts.push({label:'進入門廳（導覽輔助）',action:()=>this.enter(null,b)});
 this.open(b.name,`${b.enterable?'本版有 '+b.floors+' 個可行走樓層、實體樓梯與樓層轉場面板。':'本版僅開放外部探索。'}\n${b.id==='E'?'工管系任務位於 5F 系辦服務點與 6F 教學實驗室。':''}\n\n建築立面參考公開照片；平面、層高、設備和標示位置為重建設定，不是現場導航或竣工圖。`,opts);this.changed();}
 interact(id=null){let t=id?this.targetFor(id):this.nearest();if(!t||Math.abs(this.player.y-t.y)>.92){this.toast('請先到正確樓層，再靠近標記互動。');return false;}if(M.dist(this.player,t)>4.3){this.toast('請靠近標記後互動。');return false;}if(t.id.startsWith('LIFT_')){let b=D.buildings.find(b=>b.id===t.building);this.open(b.name+'｜樓層轉場',`目前 ${t.floor}F。可沿旁邊的雙跑樓梯逐階移動，或選擇樓層進行淡出轉場。\n\n這是 VR 舒適移動功能，不模擬真實電梯轎廂或機械運轉。`,Array.from({length:b.floors},(_,i)=>({label:`${i+1}F${b.id==='E'?(i===4?' · 工管系報到':i===5?' · 智慧製造實驗室':''):''}${i+1===t.floor?'（目前）':''}`,action:()=>this.lift(b.id,i+1)})));this.log('floor_panel',{building:b.id,floor:t.floor});return true;}
 if(t.id==='OFFICE5'){this.open('工管系 5F｜新生報到',this.state.quest===0?'歡迎加入工業工程與管理系。\n你已實際到達模型的五樓；接著探索校園、完成物流任務，再到六樓進行 5S、瓶頸與品質練習。':'報到紀錄已保存。六樓的智慧製造教學實驗室提供後續任務。',this.state.quest===0?[{label:'完成工管新生報到',action:()=>{this.complete();this.close();}}]:[]);return true;}
 let hit=this.world.physics.segment([this.player.x,this.player.y+1.3,this.player.z],[t.x,t.y+1.1,t.z]);if(hit&&hit.type==='wall'&&hit.t<.80){this.toast('中間有牆或設備，請繞到標記前方。');return false;}return super.interact(t.id);}
 menu(){let loc=this.location(),q=CQ.QUESTS[this.state.quest];this.open('工管學生｜探索平板',this.questText+'\n'+(q?.desc||'本日任務完成。')+`\n\n${loc.title}｜模型高度 ${this.player.y.toFixed(2)} m\n經驗 ${this.state.xp} XP｜已探索 ${this.state.visited.length}/14 棟。\n進度只保存在此瀏覽器，跨裝置不會自動同步。`,[{label:'前往校門（導覽輔助）',action:()=>{this.cart.driving=false;this.teleport(D.spawn.x,D.spawn.z,{assist:true,kind:'menu-gate'});this.close();}},{label:'理工大樓門廳（導覽輔助）',action:()=>this.enter(null,D.buildings.find(b=>b.id==='E'))},{label:'理工 5F 報到（導覽輔助）',action:()=>this.lift('E',5)},{label:'理工 6F 實驗室（導覽輔助）',action:()=>this.lift('E',6)}]);}
}
CQ.Game=Game;
})();
