'use strict';
(()=>{
const D=CQ.DATA,M=CQ.M;
CQ.QUESTS=[
 {title:'01 新生報到',desc:'走進校園，到理工大樓的工管入口辦理報到。',xp:100},
 {title:'02 我的校園地圖',desc:'與教學大樓、設計大樓、圖書館入口互動，完成三處探索。',xp:150},
 {title:'03 物流順路挑戰',desc:'到校門旁物流點領取材料，配送圖書館、管理大樓、設計大樓，再回理工大樓。',xp:200},
 {title:'04 讓工作站井然有序',desc:'進入理工大樓示意實驗室，拾取 3 件物品並送到正確的 5S 分類區。',xp:200},
 {title:'05 找出產線瓶頸',desc:'觀察 A、B、C 三站，再選擇一站的改善方案，降低 12 件工單的完工時間。',xp:250},
 {title:'06 品質把關',desc:'到實驗室檢驗台，依 10.00 ± 0.10 mm 判斷 8 個樣本。',xp:200}
];
CQ.defaultState=()=>({schema:2,quest:0,xp:0,visited:[],signed:[],done:[],assists:0,playSeconds:0,route:{active:false,pickup:false,delivered:[],distance:0,assisted:false,best:null},fiveS:{sorted:[],held:null,attempts:0},seenStations:[],upgraded:false,qc:{index:0,correctFirst:0,totalAttempts:0,attemptOnCurrent:0},log:[]});
function loadState(){try{let s=JSON.parse(localStorage.getItem('cyut-campusquest-v2'));if(!s||s.schema!==2)return null;let d=CQ.defaultState();for(let k of ['quest','xp','assists','playSeconds'])if(!Number.isFinite(s[k]))return null;if(s.quest<0||s.quest>6)return null;for(let k of ['visited','signed','done','log','seenStations'])if(!Array.isArray(s[k]))return null;if(!s.route||!Array.isArray(s.route.delivered)||!s.fiveS||!Array.isArray(s.fiveS.sorted)||!s.qc||!Number.isFinite(s.qc.index)||s.qc.index<0||s.qc.index>8)return null;s.log=s.log.slice(-5000);return Object.assign(d,s);}catch{return null;}}
class Game{
 constructor(){this.state=loadState()||CQ.defaultState();this.player={...D.spawn,scene:'campus'};this.outdoorReturn=null;this.worlds={};this.world=this.getWorld('campus');this.started=false;this.firstPerson=false;this.overview=false;this.moving=false;this.dialog=null;this.navOverride=null;this.cart={x:18,z:188,yaw:0,driving:false,speed:0};this.toastText='';this.lastSave=0;this.mode='desktop';}
 getWorld(key){return this.worlds[key]||(this.worlds[key]=CQ.makeWorld(key));}
 floor(x=this.player.x,z=this.player.z){return this.player.scene==='campus'?CQ.ground(x,z):0;}
 log(type,data={}){this.state.log.push({time:new Date().toISOString(),playSeconds:+this.state.playSeconds.toFixed(2),mode:this.mode,scene:this.player.scene,type,...data});if(this.state.log.length>5000)this.state.log.shift();this.dirty=true;}
 save(){try{localStorage.setItem('cyut-campusquest-v2',JSON.stringify(this.state));this.storageOK=true;}catch{this.storageOK=false;}this.lastSave=this.state.playSeconds;}
 start(){this.started=true;this.log('session_start',{schema:2,build:D.version});this.toast('歡迎來到朝陽。先到理工大樓的金色標記報到。');this.changed();}
 reset(){this.state=CQ.defaultState();this.player={...D.spawn,scene:'campus'};this.world=this.getWorld('campus');this.cart.driving=false;this.dialog=null;this.navOverride=null;this.save();this.log('reset');this.changed();}
 toast(s){this.toastText=s;this.toastUntil=performance.now()+6500;this.onToast?.(s);}
 changed(){this.save();this.onChange?.();}
 complete(){let q=CQ.QUESTS[this.state.quest];if(!q)return;this.state.done.push(q.title);this.state.xp+=q.xp;this.log('quest_completed',{quest:this.state.quest,title:q.title,xp:q.xp});this.state.quest++;this.navOverride=null;this.toast(q.title+' 完成！ +'+q.xp+' XP');this.changed();}
 get questText(){let s=this.state,q=CQ.QUESTS[s.quest];if(!q)return'本日任務完成 · 自由探索校園';let suffix='';if(s.quest===1)suffix=` (${['T','D','L'].filter(x=>s.signed.includes(x)).length}/3)`;if(s.quest===2)suffix=s.route.pickup?` (${s.route.delivered.length}/3 已配送)`:' (尚未領取材料)';if(s.quest===3)suffix=` (${s.fiveS.sorted.length}/3)`;if(s.quest===4)suffix=` (${s.seenStations.length}/3 已觀察)`;if(s.quest===5)suffix=` (${s.qc.index}/8)`;return q.title+suffix;}
 objective(){let s=this.state,q=s.quest;if(this.navOverride&&this.player.scene==='campus')return this.targetFor(this.navOverride);if(this.player.scene!=='campus'){if(q===3){if(s.fiveS.held!==null)return this.targetFor('BIN'+s.fiveS.held);let i=[0,1,2].find(i=>!s.fiveS.sorted.includes(i));return this.targetFor('ITEM'+i);}if(q===4){let i=[0,1,2].find(i=>!s.seenStations.includes(i));return this.targetFor('ST'+(i??1));}if(q===5)return this.targetFor('QC');return this.targetFor('EXIT');}
 if(q===0)return this.targetFor('E');if(q===1)return this.targetFor(['T','D','L'].find(x=>!s.signed.includes(x))||'E');if(q===2){if(!s.route.pickup)return this.targetFor('SUPPLY');let order=s.route.best?.order||D.delivery;return this.targetFor(order.find(x=>!s.route.delivered.includes(x))||'E');}return this.targetFor('E');}
 interactables(){if(this.player.scene==='campus')return [
 {id:'WELCOME',name:'迎新學長',x:13,z:203}, {id:'SUPPLY',name:'校園物流點',x:2,z:188},{id:'CART',name:'電動搬運車',x:this.cart.x,z:this.cart.z},
 ...D.buildings.map(b=>({id:b.id,name:b.name,x:b.door[0],z:b.door[1]})),...D.places.filter(p=>!['GATE','BUS','P1','P2','P3','PLAZA'].includes(p.id))];
 let a=[{id:'EXIT',name:'返回校園',x:0,z:8.5}];if(this.player.scene==='lab'){
  for(let i=0;i<3;i++){a.push({id:'ST'+i,name:'工作站 '+'ABC'[i],x:-6+i*6,z:-5.25});a.push({id:'BIN'+i,name:['常用工具區','可回收物區','待維修隔離區'][i],x:-6+i*6,z:1.35});if(!this.state.fiveS.sorted.includes(i)&&this.state.fiveS.held!==i)a.push({id:'ITEM'+i,name:['扳手','空紙箱','損壞電纜'][i],x:-4+i*4,z:3.7});}a.push({id:'QC',name:'品質檢驗台',x:4.4,z:5.8});
 }else a.push({id:'INFO',name:this.player.scene==='classroom'?'課程主題看板':'閱讀與資料素養',x:0,z:-7.5});return a;}
 targetFor(id){return this.interactables().find(x=>x.id===id)||null;}
 nearest(){let n=null,d=Infinity;for(const t of this.interactables()){let dd=M.dist(this.player,t);if(dd<d){n=t;d=dd;}}return d<4.2?{...n,distance:d}:null;}
 canStand(x,z,r=.42){let b=this.world.bounds;return x>=b.minX&&x<=b.maxX&&z>=b.minZ&&z<=b.maxZ&&!CQ.collision(x,z,this.world.boxes,r);}
 move(dx,dz){let p=this.player,r=this.cart.driving?1.08:.42,n=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.22)),old={x:p.x,z:p.z};for(let i=0;i<n;i++){if(this.canStand(p.x+dx/n,p.z,r))p.x+=dx/n;if(this.canStand(p.x,p.z+dz/n,r))p.z+=dz/n;}let d=M.dist(old,p);if(this.state.route.active&&p.scene==='campus')this.state.route.distance+=d;if(this.cart.driving){this.cart.x=p.x;this.cart.z=p.z;this.cart.yaw=p.yaw;}return d;}
 teleport(x,z,{assist=false,kind='vr-teleport'}={}){if(!this.canStand(x,z))return false;const old={x:this.player.x,z:this.player.z};if(!assist&&!CQ.lineClear(old,{x,z},this.world.boxes))return false;if(!assist&&M.dist(old,{x,z})>16)return false;if(this.state.route.active&&this.player.scene==='campus'){this.state.route.distance+=M.dist(old,{x,z});if(assist)this.state.route.assisted=true;}if(assist)this.state.assists++;this.player.x=x;this.player.z=z;this.log('teleport',{x,z,assist,kind});this.onTeleport?.();this.changed();return true;}
 enter(key,b){this.cart.driving=false;this.cart.speed=0;this.outdoorReturn={x:b.door[0],z:b.door[1],yaw:this.player.yaw};this.player={x:0,z:7.3,yaw:0,scene:key};this.world=this.getWorld(key);this.dialog=null;this.navOverride=null;this.log('enter_interior',{building:b.id,interior:key,geometry:'authored-schematic'});this.changed();}
 exit(){let p=this.outdoorReturn||{x:-27,z:16,yaw:0};this.player={...p,scene:'campus'};this.world=this.getWorld('campus');this.dialog=null;this.log('exit_interior');this.changed();}
 open(title,body,options=[]){this.dialog={title,body,options:[...options,{label:'關閉',action:()=>this.close()}]};this.onDialog?.(this.dialog);}
 close(){this.dialog=null;this.onDialog?.(null);}
 inspectBuilding(b){let s=this.state;if(!s.visited.includes(b.id)){s.visited.push(b.id);this.log('building_discovered',{id:b.id});}if(!s.signed.includes(b.id))s.signed.push(b.id);if(s.quest===1&&['T','D','L'].every(x=>s.signed.includes(x)))this.complete();
 let opts=[];
 if(b.id==='E'&&s.quest===0)opts.push({label:'辦理工管新生報到',action:()=>{this.complete();this.close();}});
 if(s.quest===2&&s.route.pickup&&D.delivery.includes(b.id)&&!s.route.delivered.includes(b.id))opts.push({label:'交付教學材料',action:()=>{s.route.delivered.push(b.id);this.log('delivery',{building:b.id,distance:s.route.distance});this.toast('材料已交付：'+b.name);this.close();this.changed();}});
 if(b.id==='E'&&s.quest===2&&s.route.delivered.length===3)opts.push({label:'結算配送任務',action:()=>{s.route.active=false;this.log('delivery_completed',{distance:s.route.distance,best:s.route.best?.length,assisted:s.route.assisted});this.complete();this.open('配送完成',`路程：${s.route.distance.toFixed(1)} 虛擬公尺。\n格網參考最短路程：${s.route.best?.length?.toFixed(1)||'未計算'} 虛擬公尺。\n${s.route.assisted?'使用快速導覽：本次不比較路徑效率。':'數值基於遊戲示意配置，不代表真實校園距離。'}\n下一站：進入工管實驗室，完成 5S 任務。`,[{label:'進入工管教學實驗室',action:()=>this.enter('lab',b)}]);}});
 if(b.interior)opts.push({label:'進入'+({lab:'工管實驗室',classroom:'示意教室',library:'閱讀空間'}[b.interior])+'（示意）',action:()=>this.enter(b.interior,b)});
 this.open(b.name,b.info+'\n\n已完成地點探索。'+(b.id==='E'?' 入口用傳送切換至教學場景，不模擬實際電梯。':''),opts);this.changed();
 }
 interact(id=null){let t=id?this.targetFor(id):this.nearest();if(!t||M.dist(this.player,t)>4.3){this.toast('請先靠近互動標記（約 4 公尺內）。');return false;}if(this.cart.driving&&Math.abs(this.cart.speed)>.4){this.toast('請先停止搬運車再互動。');return false;}this.log('interaction',{target:t.id});if(this.navOverride===t.id)this.navOverride=null;let b=D.buildings.find(b=>b.id===t.id);if(b){this.inspectBuilding(b);return true;}
 const s=this.state;
 if(t.id==='WELCOME'){this.open('新生，歡迎來到朝陽！','你是一名工業工程與管理系學生。\n今天先到理工大樓報到，再用工管方法處理校園中的物流、整理、產線與品質問題。\n\nNPC、對話與任務為虛構教學情境；建築為簡化重建。',[{label:'開始探索',action:()=>this.close()}]);}
 else if(t.id==='SUPPLY'){if(s.quest===2&&!s.route.pickup){this.open('校園物流點','請配送三箱教學材料：圖書館、管理大樓、設計大樓。最後回到理工大樓交件。\n\n可步行；電腦版也能使用旁邊的電動搬運車。路程以遊戲座標計算。',[{label:'領取材料並開始記錄路程',action:()=>{let e=D.buildings.find(b=>b.id==='E');s.route.pickup=true;s.route.active=true;s.route.distance=0;s.route.best=CQ.deliveryPlan({x:this.player.x,z:this.player.z},D.delivery.map(id=>{let b=D.buildings.find(v=>v.id===id);return{id,x:b.door[0],z:b.door[1]};}),{x:e.door[0],z:e.door[1]},this.world.boxes);this.log('pickup',{plan:s.route.best});this.close();this.changed();this.toast('材料已裝入背包。金色導航標記指向下一站。');}}]);}else this.open('校園物流點',s.route.pickup?'材料領取狀態已記錄。請查看任務目標。':'先完成新生報到與三處校園探索，才能接取配送任務。');}
 else if(t.id==='CART')this.toggleCart();
 else if(t.id==='EXIT')this.exit();
 else if(t.id.startsWith('ITEM')){let i=Number(t.id.slice(4));if(s.quest!==3)this.open('5S 物品','這些物品會用於第 4 個任務。先完成目前任務。');else if(s.fiveS.held!==null)this.toast('手上已有物品，請先送到分類區。');else{s.fiveS.held=i;this.log('pick_5s',{item:i});this.toast('已拾取'+t.name+'。請走到合適的分類區。');this.changed();}}
 else if(t.id.startsWith('BIN')){let i=Number(t.id.slice(3));if(s.fiveS.held===null)this.open(t.name,'請先拾取地上的物品，再送到適合的區域。\n扳手 → 常用工具；空紙箱 → 可回收物；損壞電纜 → 待維修隔離。');else{s.fiveS.attempts++;let item=s.fiveS.held;this.log('sort_5s',{item,bin:i,correct:item===i});if(item===i){s.fiveS.sorted.push(item);s.fiveS.held=null;this.toast('分類正確。'+s.fiveS.sorted.length+'/3');if(s.fiveS.sorted.length===3)this.complete();}else this.toast('分類不適合。依用途、是否需要與是否損壞重新判斷。');this.changed();}}
 else if(t.id.startsWith('ST')){let i=Number(t.id.slice(2));if(s.quest===4&&!s.seenStations.includes(i))s.seenStations.push(i);let times=s.upgraded?[20,25,25]:[20,35,25],opts=[];if(s.quest===4&&s.seenStations.length===3)opts.push({label:`改善工作站 ${'ABC'[i]}（${[20,35,25][i]} → ${[15,25,20][i]} s）`,action:()=>{this.log('improve_station',{station:i,correct:i===1});if(i!==1){this.toast('這項改善沒有降低最大站時間。重新比較三站的限制。');this.close();return;}s.upgraded=true;this.complete();this.open('瓶頸改善結果',`同一批 12 件、三站依序加工、無換線／故障：\n原站時間 20 / 35 / 25 s：${CQ.flowshop([20,35,25],12)} s。\n改善後 20 / 25 / 25 s：${CQ.flowshop([20,25,25],12)} s。\n\n這是確定性流水式排程的計算值，不是校園實測績效。`);}});
 this.open('工作站 '+'ABC'[i],`加工時間：${times[i]} 秒／件。\n三站時間：${times.join(' / ')} 秒。\n已觀察 ${s.seenStations.length}/3 站。\n\n找出最大站時間，選擇能真正降低瓶頸的改善。`,opts);this.changed();}
 else if(t.id==='QC'){this.qcPanel();}
 else if(t.id==='INFO'){this.open(t.name,this.player.scene==='classroom'?'工管學習主題：\n1. 以流程圖界定問題。\n2. 以數據找出瓶頸。\n3. 比較替代方案與限制。\n4. 用可重現紀錄驗證改善。\n\n此空間不是實際教室的測繪複製。':'任務中的每個數值都應有來源：\n校園位置參考官方公開地圖；遊戲尺度、加工時間與檢驗樣本則是教學設定。\n\n不要把模型假設當成實測結果。');}
 else this.open(t.name,t.info||'校園外部探索地點；空間與景物為簡化示意。');
 return true;
 }
 qcPanel(){let s=this.state;if(s.quest<5){this.open('品質檢驗台','請先完成目前任務，再進行品質檢驗。');return;}if(s.qc.index>=D.quality.length){this.open('品質檢驗已完成',`第一次判斷正確 ${s.qc.correctFirst}/${D.quality.length} 件。\n總判斷次數 ${s.qc.totalAttempts}。\n結果可在任務選單匯出為 JSON 或 CSV。`);return;}let x=D.quality[s.qc.index];this.open('尺寸檢驗 · 樣本 '+(s.qc.index+1),`量測值：${x.toFixed(2)} mm\n規格：10.00 ± 0.10 mm\n合格區間：9.90 ≤ x ≤ 10.10 mm。\n\n請依規格判斷，不按顏色猜測。`,[{label:'合格 → 接受',action:()=>this.judgeQC(true)},{label:'不合格 → 隔離',action:()=>this.judgeQC(false)}]);}
 judgeQC(accept){let q=this.state.qc,x=D.quality[q.index],correct=accept===CQ.inSpec(x);q.totalAttempts++;q.attemptOnCurrent++;this.log('qc_judgement',{sample:q.index,value:x,accept,correct,attempt:q.attemptOnCurrent});if(correct){if(q.attemptOnCurrent===1)q.correctFirst++;q.index++;q.attemptOnCurrent=0;if(q.index===D.quality.length){this.complete();this.open('完成！你已通過今日工管任務',`品質檢驗第一次判斷正確率：${(q.correctFirst/8*100).toFixed(1)}%。\n累積經驗：${this.state.xp} XP。\n\n現在可繼續自由探索。桌面選單可匯出本機學習紀錄。`);}else this.qcPanel();}else{this.toast('再核對一次規格上下限；本次嘗試已記錄。');this.qcPanel();}this.changed();}
 toggleCart(){if(this.mode.startsWith('vr')){this.open('Quest 舒適模式','本版 VR 不提供連續車輛駕駛，以避免預設的加速與旋轉視覺刺激。\n請用左控制器握把指向地面，鬆開傳送。電腦版可駕駛搬運車。');return;}if(this.cart.driving){let candidates=[[2,0],[-2,0],[0,2.2],[0,-2.2]],spot=candidates.map(([x,z])=>({x:this.cart.x+x,z:this.cart.z+z})).find(p=>this.canStand(p.x,p.z));if(!spot){this.toast('停車位置太靠近建物，請先移到空曠處。');return;}this.cart.driving=false;this.cart.speed=0;this.player.x=spot.x;this.player.z=spot.z;this.toast('已下車。');}else if(this.player.scene==='campus'&&M.dist(this.player,this.cart)<4.3){this.cart.driving=true;this.player.x=this.cart.x;this.player.z=this.cart.z;this.player.yaw=this.cart.yaw;this.toast('W/S 加速與倒車 · A/D 轉向 · Space 煞車 · F 下車');}else this.toast('先靠近校門旁的電動搬運車。');this.log('vehicle',{driving:this.cart.driving});this.changed();}
 menu(){let q=CQ.QUESTS[this.state.quest];this.open('學生任務平板',this.questText+'\n'+(q?.desc||'所有任務完成，可自由探索。')+`\n\n經驗 ${this.state.xp} XP｜探索 ${this.state.visited.length}/${D.buildings.length} 棟。\n所有紀錄留在本機瀏覽器。`,[{label:'返回校門（導覽輔助）',action:()=>{if(this.player.scene!=='campus')this.exit();this.cart.driving=false;this.teleport(D.spawn.x,D.spawn.z,{assist:true,kind:'menu-gate'});this.close();}},{label:'回到理工入口（導覽輔助）',action:()=>{if(this.player.scene!=='campus')this.exit();this.cart.driving=false;this.teleport(-27,16,{assist:true,kind:'menu-iem'});this.close();}}]);}
 export(kind){let report={app:'CYUT Campus Quest',build:D.version,exported:new Date().toISOString(),notice:'教學遊戲紀錄；校園尺度與任務數值均非實測。沒有姓名或學號。',state:this.state};let text=JSON.stringify(report,null,2),type='application/json',name='CYUT_CampusQuest_progress.json';if(kind==='csv'){let esc=s=>'"'+String(s??'').replaceAll('"','""')+'"';let rows=[['time','playSeconds','mode','scene','event','details'],...this.state.log.map(({time,playSeconds,mode,scene,type,...data})=>[time,playSeconds,mode,scene,type,JSON.stringify(data)])];text='\uFEFF'+rows.map(r=>r.map(esc).join(',')).join('\r\n');type='text/csv;charset=utf-8';name='CYUT_CampusQuest_events.csv';}let a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),10000);}
}
CQ.Game=Game;
})();
