'use strict';
/* CampusQuest local WebGL2 renderer, v2.
 * GGX microfacet BRDF, authored albedo + normal/roughness arrays, linear workflow,
 * ACES-inspired display transform, PCF directional shadows and analytic sky.
 * No CDN, runtime fetch, external engine, analytics, or third-party assets.
 */
(()=>{
const M=CQ.M;
M.ortho=(l,r,b,t,n,f)=>new Float32Array([2/(r-l),0,0,0,0,2/(t-b),0,0,0,0,-2/(f-n),0,-(r+l)/(r-l),-(t+b)/(t-b),-(f+n)/(f-n),1]);
M.inverse=a=>{let rows=Array.from({length:4},(_,i)=>Array.from({length:8},(_,j)=>j<4?a[j*4+i]:+(j-4===i)));for(let c=0;c<4;c++){let best=c;for(let j=c+1;j<4;j++)if(Math.abs(rows[j][c])>Math.abs(rows[best][c]))best=j;[rows[c],rows[best]]=[rows[best],rows[c]];let p=rows[c][c];if(Math.abs(p)<1e-12)return M.identity();for(let j=0;j<8;j++)rows[c][j]/=p;for(let i=0;i<4;i++)if(i!==c){let k=rows[i][c];for(let j=0;j<8;j++)rows[i][j]-=k*rows[c][j];}}return new Float32Array(Array.from({length:16},(_,i)=>rows[i%4][4+(i>>2)]));};
const UV=(p,n)=>Math.abs(n[1])>.5?[p[0],p[2]]:Math.abs(n[0])>.5?[p[2],p[1]]:[p[0],p[1]];
class Geometry{
 constructor(){this.v=[];this.material=0;}
 vertex(p,n,c,uv,mat){this.v.push(...p,...n,...c.slice(0,3),...uv,mat??c.mat??this.material);}
 tri(a,b,c,color,normal,uvs,mat){let n=normal||M.norm(M.cross(M.sub(b,a),M.sub(c,a)));for(let i=0;i<3;i++){let p=[a,b,c][i];this.vertex(p,n,color,uvs?.[i]||UV(p,n),mat);}}
 quad(a,b,c,d,col,n,uvs,mat){this.tri(a,b,c,col,n,uvs?.slice(0,3),mat);this.tri(a,c,d,col,n,uvs?[uvs[0],uvs[2],uvs[3]]:null,mat);return this;}
 box(x,y,z,w,h,d,col,ry=0,mat){let t=M.trs(x,y,z,ry),p=[];for(const q of [[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]])p.push(M.point(t,[q[0]*w/2,q[1]*h/2,q[2]*d/2]));for(const f of [[0,3,2,1],[4,5,6,7],[0,4,7,3],[1,2,6,5],[3,7,6,2],[0,1,5,4]])this.quad(...f.map(i=>p[i]),col,null,null,mat);return this;}
 cylinder(x,y,z,r,h,col,n=16,r2=r,mat){for(let i=0;i<n;i++){let a=i*2*Math.PI/n,b=(i+1)*2*Math.PI/n,p=[x+r*Math.cos(a),y-h/2,z+r*Math.sin(a)],q=[x+r*Math.cos(b),y-h/2,z+r*Math.sin(b)],u=[x+r2*Math.cos(a),y+h/2,z+r2*Math.sin(a)],v=[x+r2*Math.cos(b),y+h/2,z+r2*Math.sin(b)],slope=(r-r2)/h;let na=M.norm([Math.cos(a),slope,Math.sin(a)]),nb=M.norm([Math.cos(b),slope,Math.sin(b)]);for(let [p0,n0] of [[p,na],[u,na],[v,nb],[p,na],[v,nb],[q,nb]])this.vertex(p0,n0,col,UV(p0,n0),mat);this.tri([x,y+h/2,z],v,u,col,[0,1,0],null,mat);this.tri([x,y-h/2,z],p,q,col,[0,-1,0],null,mat);}return this;}
 sphere(x,y,z,rx,ry,rz,col,n=16,m=10,mat){let p=(i,j)=>[x+rx*Math.sin(j*Math.PI/m)*Math.cos(i*Math.PI*2/n),y+ry*Math.cos(j*Math.PI/m),z+rz*Math.sin(j*Math.PI/m)*Math.sin(i*Math.PI*2/n)];let add=(i,j)=>{let a=p(i,j),normal=M.norm([(a[0]-x)/rx/rx,(a[1]-y)/ry/ry,(a[2]-z)/rz/rz]);this.vertex(a,normal,col,[i/n,j/m],mat);};for(let i=0;i<n;i++)for(let j=0;j<m;j++)for(let [ii,jj] of [[i,j],[i+1,j],[i+1,j+1],[i,j],[i+1,j+1],[i,j+1]])add(ii,jj);return this;}
 beam(a,b,r,col,n=8,mat){let axis=M.norm(M.sub(b,a)),u=M.norm(M.cross(axis,Math.abs(axis[1])>.9?[1,0,0]:[0,1,0])),v=M.cross(axis,u);for(let i=0;i<n;i++){let q=i*2*Math.PI/n,s=(i+1)*2*Math.PI/n,na=M.add(M.scale(u,Math.cos(q)),M.scale(v,Math.sin(q))),nb=M.add(M.scale(u,Math.cos(s)),M.scale(v,Math.sin(s)));let pa=M.add(a,M.scale(na,r)),pb=M.add(a,M.scale(nb,r)),qa=M.add(b,M.scale(na,r)),qb=M.add(b,M.scale(nb,r));for(let [p,nn] of [[pa,na],[qa,na],[qb,nb],[pa,na],[qb,nb],[pb,nb]])this.vertex(p,nn,col,UV(p,nn),mat);}return this;}
 ring(x,y,z,rx,rz,width,col,n=72,mat){for(let i=0;i<n;i++){let a=i*2*Math.PI/n,b=(i+1)*2*Math.PI/n,p=(u,ox,oz)=>{let px=x+ox*Math.cos(u),pz=z+oz*Math.sin(u);return [px,y===null?CQ.ground(px,pz)+.15:y,pz];};this.quad(p(a,rx,rz),p(b,rx,rz),p(b,rx-width,rz-width),p(a,rx-width,rz-width),col,[0,1,0],null,mat);}return this;}
 road(a,b,width,col,offset=.055,mat){let len=M.dist(a,b),n=Math.max(1,Math.ceil(len/2)),dx=(b.x-a.x)/len,dz=(b.z-a.z)/len;for(let i=0;i<n;i++){let t=i/n,u=(i+1)/n,p=[a.x+(b.x-a.x)*t,a.z+(b.z-a.z)*t],q=[a.x+(b.x-a.x)*u,a.z+(b.z-a.z)*u],v=(r,s)=>[r[0]-dz*width/2*s,CQ.ground(r[0]-dz*width/2*s,r[1]+dx*width/2*s)+offset,r[1]+dx*width/2*s];this.quad(v(p,1),v(q,1),v(q,-1),v(p,-1),col,[0,1,0],null,mat);}return this;}
 plane(x,z,w,d,col,y=null,offset=.025,mat){let n=y===null?Math.max(1,Math.ceil(Math.max(w,d)/4.5)):1;for(let i=0;i<n;i++)for(let j=0;j<n;j++){let a=x-w/2+w*i/n,b=z-d/2+d*j/n,ww=w/n,dd=d/n,p=(u,v)=>[u,(y===null?CQ.ground(u,v):y)+offset,v];this.quad(p(a,b),p(a,b+dd),p(a+ww,b+dd),p(a+ww,b),col,y===null?null:[0,1,0],null,mat);}return this;}
 append(src,t=M.identity()){for(let i=0;i<src.v.length;i+=12){let p=M.point(t,src.v.slice(i,i+3)),n=M.norm(M.dir(t,src.v.slice(i+3,i+6)));this.v.push(...p,...n,...src.v.slice(i+6,i+12));}return this;}
}
const VS=`#version 300 es
precision highp float;
layout(location=0) in vec3 aPosition;layout(location=1) in vec3 aNormal;layout(location=2) in vec3 aColor;layout(location=3) in vec2 aUV;layout(location=4) in float aMaterial;
uniform mat4 uVP,uModel,uLightVP;out vec3 vPos,vNormal,vColor;out vec2 vUV;flat out int vMat;out vec4 vLight;
void main(){vec4 p=uModel*vec4(aPosition,1.);vPos=p.xyz;vNormal=normalize(mat3(uModel)*aNormal);vColor=aColor;vUV=aUV;vMat=int(aMaterial+.5);vLight=uLightVP*p;gl_Position=uVP*p;}`;
const FS=`#version 300 es
precision highp float;precision highp sampler2DArray;precision highp sampler2DShadow;
in vec3 vPos,vNormal,vColor;in vec2 vUV;flat in int vMat;in vec4 vLight;
uniform sampler2DArray uAlbedo,uNormal;uniform sampler2DShadow uShadow;uniform vec3 uEye,uSun;uniform float uShadowOn,uTime,uExposure,uDay,uQuality;out vec4 frag;
const float PI=3.14159265;
vec3 tone(vec3 x){return clamp((x*(2.51*x+.03))/(x*(2.43*x+.59)+.14),0.,1.);}
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
float n2(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+1.),f.x),f.y);}
float texScale(int m){if(m==1)return .38;if(m==2)return .24;if(m==3)return .55;if(m==4)return .25;if(m==5)return .20;if(m==6)return .48;if(m==7)return .55;if(m==8)return .33;if(m==14)return .48;return .5;}
vec3 env(vec3 d){float s=pow(max(dot(d,uSun),0.),128.);vec3 c=mix(vec3(.52,.60,.61),vec3(.10,.29,.51),pow(max(d.y,0.),.4));float clouds=smoothstep(.50,.73,n2(d.xz/(max(d.y,.06))*.85));c=mix(c,vec3(.8,.83,.82),clouds*.43*smoothstep(0.,.3,d.y));c+=vec3(1.,.81,.57)*s*1.6;return mix(vec3(.025,.035,.065),c,uDay);}
float shadow(vec3 N){if(uShadowOn<.5)return 1.;vec3 q=vLight.xyz/vLight.w*.5+.5;if(any(lessThan(q,vec3(.001)))||any(greaterThan(q,vec3(.999))))return 1.;float bias=max(.00015,.0006*(1.-dot(N,uSun)));float r=0.;vec2 size=vec2(textureSize(uShadow,0));for(int i=-1;i<=1;i++)for(int j=-1;j<=1;j++)r+=texture(uShadow,vec3(q.xy+vec2(i,j)/size,q.z-bias));return r/9.;}
void main(){int m=vMat;if(m==10&&!gl_FrontFacing)discard;vec2 uv=(m==11)?vUV:vUV*texScale(m);vec4 al=m==0?vec4(1):texture(uAlbedo,vec3(uv,float(m)));if(m==11&&al.a<.42)discard;
vec3 base=pow(max(al.rgb*vColor,vec3(.002)),vec3(2.2));vec3 N=normalize(vNormal);if(!gl_FrontFacing)N=-N;
vec4 nm=texture(uNormal,vec3(uv,float(m)));float rough=m==0?.78:max(.12,nm.a);float metal=m==9?.78:0.;
if(m!=0&&m!=10&&m!=11&&m!=12&&uQuality>.2){vec3 q1=dFdx(vPos),q2=dFdy(vPos);vec2 st1=dFdx(uv),st2=dFdy(uv);vec3 T=q1*st2.y-q2*st1.y;T=normalize(T-N*dot(N,T)+vec3(.000001));vec3 B=normalize(cross(N,T));vec3 nn=nm.xyz*2.-1.;nn.xy*=.45;N=normalize(mat3(T,B,N)*nn);}
vec3 V=normalize(uEye-vPos),L=uSun,H=normalize(V+L);float nv=max(dot(N,V),.001),nl=max(dot(N,L),0.);float sh=shadow(N);
if(m==12){N=normalize(vec3(sin(vPos.x*1.9+uTime)*.065,1.,cos(vPos.z*1.4-uTime*1.2)*.06));rough=.12;nl=max(dot(N,L),0.);nv=max(dot(N,V),.001);H=normalize(V+L);base=vec3(.018,.082,.068);}
vec3 F0=mix(vec3(.04),base,metal);float hv=max(dot(H,V),0.),a=rough*rough,a2=a*a,nh=max(dot(N,H),0.),D=a2/(PI*pow(nh*nh*(a2-1.)+1.,2.)+.000001);vec3 F=F0+(1.-F0)*pow(1.-hv,5.);float k=pow(rough+1.,2.)/8.,G=(nv/(nv*(1.-k)+k))*(nl/(nl*(1.-k)+k));vec3 spec=D*F*G/(4.*nv*nl+.0001);vec3 diff=(1.-F)*(1.-metal)*base/PI;
float skyFactor=.63+.37*max(N.y,0.);vec3 amb=mix(vec3(.25,.25,.20),vec3(.52,.65,.83),clamp(N.y*.5+.5,0.,1.))*base*skyFactor*.75;
vec3 c=amb+(diff+spec)*vec3(3.0,2.72,2.27)*nl*sh*uDay;
if(m==11){c=base*(.60+.70*nl*sh)*vec3(.95,1.05,.78);c+=base*pow(max(dot(-L,V),0.),3.)*.6;}
if(m==10){vec3 R=reflect(-V,N);float fr=.18+.82*pow(1.-nv,5.);vec3 inside=vec3(.034,.055,.064)*(.5+.5*n2(vPos.xy*.25));c=mix(inside,env(R)*.73,fr);c+=vec3(.32,.42,.42)*pow(max(dot(R,L),0.),350.)*.5;}
if(m==12)c=mix(c,env(reflect(-V,N)),.28+.6*pow(1.-nv,5.));if(m==13)c=pow(vColor,vec3(2.2))*1.7;
float fog=1.-exp(-pow(length(vPos-uEye)/1050.,1.8));vec3 sky=env(normalize(vPos-uEye));c=mix(c,sky,fog);frag=vec4(pow(tone(max(c,vec3(0.))*uExposure),vec3(1./2.2)),1.);}`;
const SVS=`#version 300 es
precision highp float;layout(location=0)in vec3 aPosition;layout(location=3)in vec2 aUV;layout(location=4)in float aMaterial;uniform mat4 uVP;out vec2 uv;flat out int mat;void main(){gl_Position=uVP*vec4(aPosition,1);uv=aUV;mat=int(aMaterial+.5);}`;
const SFS=`#version 300 es
precision highp float;precision highp sampler2DArray;in vec2 uv;flat in int mat;uniform sampler2DArray uAlbedo;void main(){if(mat==11&&texture(uAlbedo,vec3(uv,11)).a<.42)discard;}`;
const BVS=`#version 300 es
precision highp float;out vec2 uv;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);uv=p;gl_Position=vec4(p*2.-1.,1.,1.);}`;
const BFS=`#version 300 es
precision highp float;in vec2 uv;uniform mat4 invVP;uniform vec3 eye,sun;uniform float day;out vec4 frag;
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+1.),f.x),f.y);}float fb(vec2 p){return n(p)*.54+n(p*2.03)*.29+n(p*4.01)*.13+n(p*8.1)*.04;}
void main(){vec4 w=invVP*vec4(uv*2.-1.,1,1);vec3 d=normalize(w.xyz/w.w-eye);float h=max(d.y,0.);vec3 c=mix(vec3(.73,.78,.76),vec3(.25,.49,.70),pow(h,.38));float sunD=max(dot(d,sun),0.);c+=vec3(.72,.51,.24)*pow(sunD,100.);c+=vec3(.75,.69,.58)*pow(sunD,1800.);vec2 p=d.xz/(max(d.y,.04))*.8;float cl=fb(p+vec2(2.4,8.)),mask=smoothstep(.51,.68,cl)*smoothstep(0.,.15,h);c=mix(c,vec3(.90,.90,.85)*(.88+.12*cl),mask*.88);c=mix(vec3(.024,.034,.064),c,day);frag=vec4(c,1);}`;
const TVS=`#version 300 es
precision highp float;layout(location=0)in vec3 aPosition;layout(location=1)in vec2 aUV;uniform mat4 uVP,uModel;out vec2 vUV;void main(){vUV=aUV;gl_Position=uVP*uModel*vec4(aPosition,1);}`;
const TFS=`#version 300 es
precision highp float;in vec2 vUV;uniform sampler2D uTex;out vec4 frag;void main(){frag=texture(uTex,vUV);if(frag.a<.025)discard;}`;
function program(gl,vs,fs){let p=gl.createProgram();for(const [type,src]of[[gl.VERTEX_SHADER,vs],[gl.FRAGMENT_SHADER,fs]]){let s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));gl.attachShader(p,s);gl.deleteShader(s);}gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p;}
class Renderer{
 constructor(canvas){this.canvas=canvas;let gl=canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance',xrCompatible:true});if(!gl)throw Error('需要 WebGL 2；請在 Chrome／Edge 啟用圖形加速。');this.gl=gl;this.p=program(gl,VS,FS);this.tp=program(gl,TVS,TFS);this.sp=program(gl,SVS,SFS);this.bp=program(gl,BVS,BFS);this.U={};for(let k of ['uVP','uModel','uEye','uSun','uTime','uExposure','uDay','uQuality','uShadowOn','uLightVP','uShadow','uAlbedo','uNormal'])this.U[k]=gl.getUniformLocation(this.p,k);this.T={};for(let k of ['uVP','uModel','uTex'])this.T[k]=gl.getUniformLocation(this.tp,k);this.B={};for(let k of ['invVP','eye','sun','day'])this.B[k]=gl.getUniformLocation(this.bp,k);this.identity=M.identity();this.sun=M.norm([-.72,.93,.56]);this.lightVP=M.identity();this.day=1;this.exposure=1.0;this.quality=1;this.pixelScale=1;this.drawCalls=0;this.triangles=0;this.assetsReady=false;this.shadowOn=false;this.lastShadow=-1e5;this.emptyVAO=gl.createVertexArray();
 this.qvao=gl.createVertexArray();gl.bindVertexArray(this.qvao);let b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-.5,-.5,0,0,1,.5,-.5,0,1,1,.5,.5,0,1,0,-.5,-.5,0,0,1,.5,.5,0,1,0,-.5,.5,0,0,0]),gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,20,0);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,2,gl.FLOAT,false,20,12);gl.bindVertexArray(null);this.initShadow(2048);this.ready=this.initMaterials();}
 async initMaterials(){let gl=this.gl,N=512,L=16;this.maps=[];for(let k=0;k<2;k++){let t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D_ARRAY,t);gl.texStorage3D(gl.TEXTURE_2D_ARRAY,10,gl.RGBA8,N,N,L);gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_WRAP_T,gl.REPEAT);let init=new Uint8Array(N*N*4);for(let j=0;j<init.length;j+=4){init[j]=k?128:255;init[j+1]=k?128:255;init[j+2]=255;init[j+3]=255;}for(let j=0;j<L;j++)gl.texSubImage3D(gl.TEXTURE_2D_ARRAY,0,0,0,j,N,N,1,gl.RGBA,gl.UNSIGNED_BYTE,init);gl.generateMipmap(gl.TEXTURE_2D_ARRAY);this.maps.push(t);}
 await Promise.all(CQ.TEXTURE_DATA.flatMap((pair,i)=>pair.map((url,k)=>new Promise(resolve=>{let im=new Image();im.onload=()=>{gl.bindTexture(gl.TEXTURE_2D_ARRAY,this.maps[k]);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);gl.texSubImage3D(gl.TEXTURE_2D_ARRAY,0,0,0,i,N,N,1,gl.RGBA,gl.UNSIGNED_BYTE,im);resolve();};im.onerror=()=>{console.warn('材質載入失敗',i,k);resolve();};im.src=url;}))));for(let t of this.maps){gl.bindTexture(gl.TEXTURE_2D_ARRAY,t);gl.generateMipmap(gl.TEXTURE_2D_ARRAY);let ext=gl.getExtension('EXT_texture_filter_anisotropic');if(ext)gl.texParameterf(gl.TEXTURE_2D_ARRAY,ext.TEXTURE_MAX_ANISOTROPY_EXT,Math.min(4,gl.getParameter(ext.MAX_TEXTURE_MAX_ANISOTROPY_EXT)));}this.assetsReady=true;this.lastShadow=-1e5;}
 initShadow(size){let gl=this.gl;if(this.shadowTex)gl.deleteTexture(this.shadowTex);if(this.shadowFBO)gl.deleteFramebuffer(this.shadowFBO);this.shadowSize=size;this.shadowTex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.shadowTex);gl.texImage2D(gl.TEXTURE_2D,0,gl.DEPTH_COMPONENT24,size,size,0,gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_COMPARE_MODE,gl.COMPARE_REF_TO_TEXTURE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_COMPARE_FUNC,gl.LEQUAL);this.shadowFBO=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,this.shadowFBO);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,this.shadowTex,0);gl.drawBuffers([gl.NONE]);gl.readBuffer(gl.NONE);this.shadowSupported=gl.checkFramebufferStatus(gl.FRAMEBUFFER)===gl.FRAMEBUFFER_COMPLETE;gl.bindFramebuffer(gl.FRAMEBUFFER,null);}
 upload(geo,dynamic=false){let gl=this.gl,mesh={vao:gl.createVertexArray(),buffer:gl.createBuffer(),count:geo.v.length/12,dynamic};gl.bindVertexArray(mesh.vao);gl.bindBuffer(gl.ARRAY_BUFFER,mesh.buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(geo.v),dynamic?gl.DYNAMIC_DRAW:gl.STATIC_DRAW);for(let [i,n,o]of[[0,3,0],[1,3,12],[2,3,24],[3,2,36],[4,1,44]]){gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,n,gl.FLOAT,false,48,o);}gl.bindVertexArray(null);return mesh;}
 update(mesh,geo){let gl=this.gl;mesh.count=geo.v.length/12;gl.bindBuffer(gl.ARRAY_BUFFER,mesh.buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(geo.v),gl.DYNAMIC_DRAW);}
 texture(canvas){let gl=this.gl,t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);this.updateTexture(t,canvas);return t;}
 updateTexture(t,c){let gl=this.gl;gl.bindTexture(gl.TEXTURE_2D,t);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,c);}
 updateShadow(chunks,center,t,overview=false){if(!this.shadowSupported||!this.assetsReady||this.quality<.1){this.shadowOn=false;return;}let move=this.shadowCenter?Math.hypot(center[0]-this.shadowCenter[0],center[2]-this.shadowCenter[2]):1e9;if(t-this.lastShadow<750||(move<9&&t-this.lastShadow<10000))return;this.lastShadow=t;this.shadowCenter=center.slice();let radius=overview?340:125,tar=[center[0],center[1],center[2]],eye=M.add(tar,M.scale(this.sun,300));this.lightVP=M.mul(M.ortho(-radius,radius,-radius,radius,1,640),M.look(eye,tar));let gl=this.gl;gl.bindFramebuffer(gl.FRAMEBUFFER,this.shadowFBO);gl.viewport(0,0,this.shadowSize,this.shadowSize);gl.clear(gl.DEPTH_BUFFER_BIT);gl.colorMask(false,false,false,false);gl.enable(gl.DEPTH_TEST);gl.depthMask(true);gl.disable(gl.CULL_FACE);gl.useProgram(this.sp);gl.uniformMatrix4fv(gl.getUniformLocation(this.sp,'uVP'),false,this.lightVP);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D_ARRAY,this.maps[0]);gl.uniform1i(gl.getUniformLocation(this.sp,'uAlbedo'),0);for(let c of chunks){if(c.noShadow)continue;if(c.center&&Math.hypot(c.center[0]-center[0],c.center[2]-center[2])>radius+(c.radius||80)+120)continue;let mesh=c.lodMesh&&Math.hypot(c.center[0]-center[0],c.center[2]-center[2])>140?c.lodMesh:c.mesh;gl.bindVertexArray(mesh.vao);gl.drawArrays(gl.TRIANGLES,0,mesh.count);}gl.colorMask(true,true,true,true);gl.bindFramebuffer(gl.FRAMEBUFFER,null);this.shadowOn=true;}
 begin(vp,eye,clear=true){let gl=this.gl;this.vp=vp;this.eye=eye;if(clear){gl.clearColor(.64,.73,.79,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);}gl.disable(gl.DEPTH_TEST);gl.depthMask(false);gl.disable(gl.BLEND);gl.useProgram(this.bp);gl.bindVertexArray(this.emptyVAO);gl.uniformMatrix4fv(this.B.invVP,false,M.inverse(vp));gl.uniform3fv(this.B.eye,eye);gl.uniform3fv(this.B.sun,this.sun);gl.uniform1f(this.B.day,this.day);gl.drawArrays(gl.TRIANGLES,0,3);gl.enable(gl.DEPTH_TEST);gl.depthMask(true);gl.disable(gl.CULL_FACE);gl.useProgram(this.p);gl.uniformMatrix4fv(this.U.uVP,false,vp);gl.uniformMatrix4fv(this.U.uLightVP,false,this.lightVP);gl.uniform3fv(this.U.uEye,eye);gl.uniform3fv(this.U.uSun,this.sun);gl.uniform1f(this.U.uExposure,this.exposure);gl.uniform1f(this.U.uDay,this.day);gl.uniform1f(this.U.uQuality,this.quality);gl.uniform1f(this.U.uTime,performance.now()/1000);gl.uniform1f(this.U.uShadowOn,this.shadowOn?1:0);gl.uniform1i(this.U.uAlbedo,0);gl.uniform1i(this.U.uNormal,1);gl.uniform1i(this.U.uShadow,2);this.drawCalls=1;this.triangles=1;}
 draw(mesh,model=this.identity){if(!mesh?.count)return;let gl=this.gl;gl.useProgram(this.p);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D_ARRAY,this.maps[0]);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D_ARRAY,this.maps[1]);gl.activeTexture(gl.TEXTURE2);gl.bindTexture(gl.TEXTURE_2D,this.shadowTex);gl.uniformMatrix4fv(this.U.uModel,false,model);gl.bindVertexArray(mesh.vao);gl.drawArrays(gl.TRIANGLES,0,mesh.count);this.drawCalls++;this.triangles+=mesh.count/3;}
 label(tex,model,onTop=false){let gl=this.gl;gl.useProgram(this.tp);gl.uniformMatrix4fv(this.T.uVP,false,this.vp);gl.uniformMatrix4fv(this.T.uModel,false,model);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,tex);gl.uniform1i(this.T.uTex,0);gl.bindVertexArray(this.qvao);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);if(onTop)gl.disable(gl.DEPTH_TEST);gl.drawArrays(gl.TRIANGLES,0,6);gl.enable(gl.DEPTH_TEST);gl.depthMask(true);gl.disable(gl.BLEND);this.drawCalls++;}
 resize(){let d=Math.min(window.devicePixelRatio||1,1.5)*this.pixelScale,w=Math.round(innerWidth*d),h=Math.round(innerHeight*d);if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;}this.gl.viewport(0,0,w,h);}
}
CQ.G=Geometry;CQ.Renderer=Renderer;
CQ.makeText=(title,sub='',w=768,h=144)=>{let c=document.createElement('canvas');c.width=w;c.height=h;let ctx=c.getContext('2d');ctx.fillStyle='rgba(20,29,28,.93)';ctx.beginPath();ctx.roundRect(2,2,w-4,h-4,8);ctx.fill();ctx.fillStyle='#c4ac78';ctx.fillRect(19,24,4,h-48);ctx.fillStyle='#f0eee7';ctx.font='500 43px system-ui,"Microsoft JhengHei",sans-serif';ctx.textAlign='center';ctx.fillText(title,w/2,sub?64:88,w-65);if(sub){ctx.fillStyle='#bfcac4';ctx.font='23px system-ui,sans-serif';ctx.fillText(sub,w/2,108,w-60);}return c;};
})();
