'use strict';const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('node:assert/strict');global.window=global;const store=new Map();global.localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)};let root=path.join(__dirname,'..');for(let f of ['data/campus.js','src/math.js','src/render.js','src/spatial.js','src/world.js','src/navigation.js','src/game.js','src/game-v2.js'])vm.runInThisContext(fs.readFileSync(path.join(root,f),'utf8'),{filename:f});let g=new CQ.Game(),w=g.world,sp=w.physics,tests=[];function test(name,fn){try{fn();tests.push({name,status:'PASS'});console.log('PASS',name);}catch(e){tests.push({name,status:'FAIL',error:e.message});console.log('FAIL',name,e.message);}}
function walk(p,x,z){let start={...p};for(let k=0;k<1500&&Math.hypot(x-p.x,z-p.z)>.012;k++){let d=Math.hypot(x-p.x,z-p.z),amount=Math.min(.07,d);sp.move(p,(x-p.x)/d*amount,(z-p.z)/d*amount);sp.gravity(p,.022);}assert(Math.hypot(x-p.x,z-p.z)<.05,JSON.stringify({goal:[x,z],stuck:p,from:start}));}
test('3D world has 62 connected authored building storeys',()=>assert.equal(w.buildingFloorCount,62));
test('Non-flat terrain has more than 25 m relief in campus',()=>assert(CQ.ground(-70,-180)-CQ.ground(8,202)>25));
test('All learning targets stand on a matching 5F/6F slab without collision',()=>{for(let t of w.learning){assert(sp.safe(t.x,t.y,t.z),t.id);assert(Math.abs(sp.support(t.x,t.z,t.y+.1).y-t.y)<.01,t.id);}});
test('Every floor-panel landing is free of colliders and supported',()=>{for(let l of w.lifts){let s=sp.support(l.x,l.z-.85,l.y+.1);assert(sp.safe(l.x,l.y,l.z-.85),l.id);assert(Math.abs(s.y-l.y)<.01,l.id);}});
test('Public entries are reachable from outside their facade',()=>{for(let b of CQ.DATA.buildings.filter(b=>b.enterable)){let q=g.safeEntrance(b),dx=Math.abs(q.x-b.x)>b.w*.4?(q.x>b.x?1:-1):0,dz=dx?0:q.z>b.z?1:-1,p={x:q.x+dx*2,z:q.z+dz*2,y:0};p.y=sp.support(p.x,p.z,b.base+.25).y;walk(p,q.x,q.z);assert(Math.abs(p.y-b.base)<.1,b.id);}});
for(let b of CQ.DATA.buildings.filter(b=>b.enterable&&b.floors>1))test('Walk both stair flights, every floor: '+b.id,()=>{let x=b.stair.x,z=b.stair.z,p={x:x-1.72,z:z+4.5,y:b.base};for(let f=0;f<b.floors-1;f++){walk(p,x-1.72,z+3);walk(p,x-1.72,z-2);walk(p,x+1.72,z-2);walk(p,x+1.72,z+4.5);assert(Math.abs(p.y-(b.base+(f+1)*3.8))<.02,JSON.stringify({floor:f+2,p}));walk(p,x-1.72,z+4.5);}});
test('Descend E6 to E1 without floor tunnelling',()=>{let b=CQ.DATA.buildings[0],x=b.stair.x,z=b.stair.z,p={x:x+1.72,z:z+4.5,y:b.base+19};for(let f=5;f>0;f--){walk(p,x+1.72,z-2);walk(p,x-1.72,z-2);walk(p,x-1.72,z+4.5);assert(Math.abs(p.y-(b.base+(f-1)*3.8))<.02);walk(p,x+1.72,z+4.5);}});
test('Cannot interact with 5F office from ground floor',()=>{let t=g.targetFor('OFFICE5');Object.assign(g.player,{x:t.x,z:t.z,y:t.y-15.2});assert.equal(g.interact('OFFICE5'),false);assert.equal(g.state.quest,0);});
test('Same floor U-shaped corridor connects three 6F stations',()=>{let t=w.learning.find(t=>t.id==='ST0'),p={...t};walk(p,-69,2);walk(p,-41,2);walk(p,-41,-.5);});
test('Window collision prevents wall traversal',()=>{let b=CQ.DATA.buildings[0],p={x:b.x+b.w/2-2,z:40,y:b.base+19};sp.move(p,5,0);assert(p.x<b.x+b.w/2);});
test('Floor transfer rejects unsupported coordinates',()=>assert.equal(g.teleport(5,230,{y:150,assist:true}),false));
test('Learned progress survives same-browser load',()=>{g.state.xp=125;g.save();assert.equal(JSON.parse(store.get('cyut-campusquest-v2')).xp,125);});
fs.writeFileSync(path.join(root,'docs/spatial-test-results.json'),JSON.stringify({engine:'Node.js '+process.version,notice:'Deterministic software tests; not physical headset verification.',tests},null,2));if(tests.some(t=>t.status==='FAIL'))process.exitCode=1;
